### ISSUE TITLE
Error in Running regions

### ISSUE THREAD

**Issue by heilandd** [dmcable/spacexr#101]
Dear SpaceXR team,

first of all congrats for this fantastic tool. Unfortunately, I run into some errors when applying the spacexr::run.CSIDE.regions() function. 

Data are Visium with regions = 3x100 selected spots

myRCTD.reps <- spacexr::run.CSIDE.regions(myRCTD=RCTD_obj, 
                                          region_list=regions, 
                                          cell_types=NULL, 
                                          gene_threshold = 5e-05, 
                                          cell_type_threshold = 10, 
                                          fdr = 0.25)

Error in `[.data.frame`(sig_genes, abs(sig_genes$p_val < p_thresh) & abs(sig_genes$log_fc) >=  : 
  promise already under evaluation: recursive default argument reference or earlier problems?
In addition: Warning messages:
1: In build.designmatrix.regions(myRCTD, region_list) :
  run.de.regions: some barcodes from region_list not found in RCTD object
2: In run.CSIDE.general(myRCTD, X1, X2, barcodes, cell_types, cell_type_threshold = cell_type_threshold,  :
  run.CSIDE.general: some parameters are set to the CSIDE vignette values, which are intended for testing but not proper execution. For more accurate results, consider using the default parameters to this function.
3: In sqrt(diag(I_val[[i]])) : NaNs produced
4: In sqrt(diag(I_val[[i]])) : NaNs produced

Thanks for your help in advance!

Best 
Henrik

**Comment by dmcable** [comment]
Hi please post or email the data.

Best,
Dylan
