### ISSUE TITLE
Where to access MERFISH raw data without cell segmentation

### ISSUE THREAD

**Issue by TianyouLuo** [dmcable/spacexr#102]
Hi,

Thank you for providing this excellent package! I am interested in the C-SIDE paper results using the MERFISH hypothalamus data without cell segmentation (Results in Fig. 5(a), 5(b) and Supp. Fig. 9(c) and 9(d)). Could you help point me to where I can find the unsegmented data and the codes you used to generated those results? I think the current shared data are already after cell segmentation, and the current figure4_merfish.Rmd file used to generate the figure directly reads in a result RDS file, but does not include codes to generate the result. Thanks!

**Comment by dmcable** [comment]
Provide your email and I will send you the required data file: volume_and_batch_correction.csv

The code is here: https://github.com/dmcable/spacexr/blob/master/AnalysisCSIDE/run_CSIDE/run_de_merfish.R

**Comment by TianyouLuo** [comment]
Thanks for the reply! I already have the file volume_and_batch_correction.csv. That is not the file that I am asking about, since that file is for data with cell segmentation. What I am trying to find is the pixel-level data without cell segmentation. If you have that, can you share it with the following email: tianyou@live.unc.edu? Thank you!

**Comment by dmcable** [comment]
The files you need are available on our data repository for our study: https://singlecell.broadinstitute.org/single_cell/study/SCP1663

Additional files for this dataset that may be relevant are available from the original MERFISH hypothalamus paper (which is cited by our study).
