### ISSUE TITLE
the pathogen as explanatory variable in CSIDE_pathology_interactions

### ISSUE THREAD

**Issue by glzhang90095** [dmcable/spacexr#104]
Hi Dylan, 
I'm trying to use the application "CSIDE_pathology_interactions" on my visium data which included fluorescent intensity output of various pathological staining. I want to see the DEGs related to the pathology. However, I didn't see any fluorescent intensity information incorporated in your code as the explanatory variable was calculated:
 _explanatory.variable <- exvar.point.density(myRCTD, barcodes, pathogen_coords, radius = 500)_

How does the "_pathogen_coords_" alone determine the pathology? 

BTW, is the radius in um here?
Thanks a lot!
Guanglin

**Comment by dmcable** [comment]
Note that you should be constructing the explanatory variable as best fit for your problem, and it is unlikely that this function as written is the best way to do it.

This function computes the density of the object, in this case a pathogen, based on the location of the object alone. If you would like to incorporate an intensity metric, then you should do the calculation differently as a weighted sum. We did this for the Alzheimer's dataset here in the function `get_plaque_density`: https://github.com/dmcable/spacexr/blob/master/AnalysisCSIDE/helper_functions/alzheimers_helper.R

The units of the radius are assumed to be the same as the units of the `myRCTD` `spatialRNA` `coords` object, so it depends on your dataset whether they would be in microns or any other unit.

**Comment by glzhang90095** [comment]
Hi Dylan,
Thanks for your quick reply.
After reviewing the related functions you directed, I still didn't fully understand all the functions very well.
For my understanding, _**get_plaque_density**_ in _**AnalysisCSIDE/j20/create_pd.R**_ was used to generate the plaque density which was used as input in _**AnalysisCSIDE/j20/pd_to_exvar.R**_. The main steps are shown below : 
Function 1. https://github.com/dmcable/spacexr/blob/8787fc1d1d24c36c093f72f947788d60f5230480/AnalysisCSIDE/j20/pd_to_exvar.R#L67-L72
Function 2. 
https://github.com/dmcable/spacexr/blob/8787fc1d1d24c36c093f72f947788d60f5230480/AnalysisCSIDE/j20/pd_to_exvar.R#L47-L53
In function 1, you used columns 1 and 2 of explanatory_variable; however, I only see column 2 in the previous lines (function 2). So I don't understand the use of rowMeans(). Is the **else** part missing in the if-else statement? 

Question 1. In my case, the output data from Visium already included pathology intensity, such as DAPI and FITC (the image below as an example). Can I use a similar way as function 1 to get the explanatory variable?
https://github.com/dmcable/spacexr/blob/8787fc1d1d24c36c093f72f947788d60f5230480/AnalysisCSIDE/j20/pd_to_exvar.R#L33-L37
Question 2. In the above, the DAPI intensity was also calculated, but I didn't see its usage in the function. What's the exact role of DAPI here? Was it used to normalize the other fluorescence intensity? 

Thanks for your time and help!
Guanglin

![image](https://user-images.githubusercontent.com/64981677/192696274-75221a78-bea0-4fe3-8892-311e9c81ef15.png)

**Comment by dmcable** [comment]
1. Your observation is correct. The code from line 30 to line 60 was manually run twice for each sample, changing the `IMAGE_NUMBER` to match the fluorescent image on either side of the spatial transcriptomics slice.
2. The DAPI channel was used to align the images to the spatial transcriptomics data.

**Comment by glzhang90095** [comment]
Hi @dmcable,

There is the following error when running the **run.CSIDE.single** when I use the whole 9 cell types. I tested the function with option _test_error = TRUE_, and it didn't report the error.  
It works when I only include a subset of cell types. However, the DEG outputs of the same cell type from various subsets are different. 
_**Error in if (any(p_val[order(p_val)] < thresh)) {: missing value where TRUE/FALSE needed Traceback**:_

My Questions about this error: 
1. How should I set up the cell type as an input?
2. How do you explain the discrepancy of DEGs across different subsets of cell types? 
3. Why test_error option can't find the error reported in the real running? It took hours to know the error.

FYI
The following is what I used in my analysis
1. I merged 2 replicates of each condition into one SpatialRNA object with sample names prefixed to barcodes as suggested by you in this post: https://github.com/dmcable/spacexr/issues/95#issue-1338024407
2. I converted the pathology intensity into an explanatory variable using code below, as suggested in your AD dataset.
```
q_level <- quantile(path_evar[,2],.90)
path.norm$exvar <- pmin(path_evar[,2], q_level) / q_level
```
3. I used the following settings for CSIDE running:
```
myRCTD@config$max_cores <- 32
myRCTD <- run.CSIDE.single(myRCTD, exvar, gene_threshold = 5e-5, cell_types =celltype,
                         cell_type_threshold = 5, fdr = 0.05, doublet_mode = FALSE, logs = TRUE)
```

I appreciate your help!

Have a good weekend!
Guanglin

**Comment by dmcable** [comment]
Hi Guanglin,

This is a known bug, but we pushed a fix over the last two days. Can you please update the package and try again? If the issue persists, please create a new Github issue (since it is a separate issue).

Dylan
