### ISSUE TITLE
de_results$gene_fits$mean_val_cor

### ISSUE THREAD

**Issue by xwanaf** [dmcable/spacexr#105]
Hi,
I'm trying to reproduce the volcano plot of the Slide-seq J20 Hippocampus data. However, it seems that when the parameter "MIN.CONV.REPLICATES" in the function "one_ct_genes" is set to 2 (default setting), the following if-else case will always be true in the function "one_ct_genes" (when other parameters are default setting):
```
if(sum(con) < MIN.CONV.REPLICATES || (use.groups && length(used_groups) < MIN.CONV.GROUPS)) {
      if(use.groups)
        de_pop[gene, ] <- c(-1, 0, 0, 0, 0, 0, rep(0, n_groups), rep(-1, n_groups))
      else
        de_pop[gene, ] <- c(-1, 0, 0, 0, 0)
    }
```
then this will occur error in the downstream codes.

When I reset "MIN.CONV.REPLICATES" to 1, the following error occurred:
```
Error in var(x): 'x' is NULL
Traceback:

1. one_ct_genes(cell_type, RCTDde_list, de_results_list, resultsdir, 
 .     cell_types_present, plot_results = plot_results, q_thresh = 0.01, 
 .     p_thresh = 1, MIN.CONV.REPLICATES = 1)
2. get_de_pop(cell_type, de_results_list, cell_prop, use.groups = use.groups, 
 .     group_ids = group_ids, MIN.CONV.REPLICATES = MIN.CONV.REPLICATES, 
 .     MIN.CONV.GROUPS = MIN.CONV.GROUPS, CT.PROP = CT.PROP)   # at line 9-10 of file <text>
3. estimate_tau(means, sds, group_ids = gid)   # at line 102 of file <text>
4. var(x)   # at line 163-168 of file <text>
5. var(x)
```
It seems that the input "means" to "estimate_tau" is NULL. And "means" is got from the following:
`means <- unlist(lapply(de_results_list[con], function(x) x$gene_fits$mean_val_cor[[cell_type]][gene]))`
Strangely, I could not find "mean_val_cor" in de_results$gene_fits.

Could you please give me some advice to fix the bug?

Regards,
xwanaf

**Comment by dmcable** [comment]
Hi, you can't set `MIN.CONV.REPLICATES` to less than 2 because at least 2 replicates with convergence are required for population DE mode.

I don't agree with your initial premise because if `MIN.CONV.REPLICATES` is set to true (and `use.groups=FALSE` by default), then the if statement will be false if there are at least two replicates that have converged (that is `sum(con) >= 2`).

**Comment by xwanaf** [comment]
I notice that `con` variable comes from 
```
con <- unlist(lapply(de_results_list, function(x)
                           ifelse(gene %in% rownames(x$gene_fits$con_mat),
                                  x$gene_fits$con_mat[gene,cell_type], FALSE)))
```
and `de_results_list[[1]]$gene_fits$con_mat` is a matrix which only contain TRUE or FALSE value. So `con` can only be TRUE or FALSE, which means `sum(con)` can only be 0 or 1?

By the way, I am using nonparametric mode on my own data, does this make any difference when running the codes plotting the volcano plot?

Best,
Xiaomeng

**Comment by xwanaf** [comment]
I realize that I only run CSIDE once and there is only one element in my `de_results_list`. That's why in my codes the if statement is always TURE.
Do you mean that we'd better run CSIDE on multiple replicates if we only have one sample? I also notice that we only have function `run.CSIDE.single` in `run.CSIDE.replicates`. Does this mean that if I would like to use the nonparametric mode, we need to repeat the whole process (including RCTD and CSIDE) several times and each time exactly the same instead of using `run.CSIDE.replicates`?

While now I have multiple replicates in `de_results_list`, I still encounter the error
```
Error in var(x): 'x' is NULL
Traceback:

1. one_ct_genes(cell_type, RCTDde_list, de_results_list, resultsdir, 
 .     cell_types_present, plot_results = plot_results, q_thresh = 0.01, 
 .     p_thresh = 1, MIN.CONV.REPLICATES = 1)
2. get_de_pop(cell_type, de_results_list, cell_prop, use.groups = use.groups, 
 .     group_ids = group_ids, MIN.CONV.REPLICATES = MIN.CONV.REPLICATES, 
 .     MIN.CONV.GROUPS = MIN.CONV.GROUPS, CT.PROP = CT.PROP)   # at line 9-10 of file <text>
3. estimate_tau(means, sds, group_ids = gid)   # at line 102 of file <text>
4. var(x)   # at line 163-168 of file <text>
5. var(x)
```
where can I find `mean_val_cor` in `de_results$gene_fits`?

Best,
xwanaf

**Comment by dmcable** [comment]
C-SIDE has two modes: single-replicate mode and population mode. If you only have one replicate, then you should not use population mode, but rather the single-replicate mode.

**Comment by xwanaf** [comment]
I notice that the codes are updated. Now I know what to do. Thank you for your help and patience!
