### ISSUE TITLE
About multiple samples in one 10X visium slide

### ISSUE THREAD

**Issue by TYCice** [dmcable/spacexr#106]
Dear developers,
Thank you for developing such convenient package!
Now I am trying RCTD to deconvolve my samples. From each slide, I have multiple samples from different group (e.g. control and test). Do I need to segment the slide to get individual sample, and then do deconvolution? Or, I can directly run RCTD on the whole slide data? 

Thank you,
Yucheng

**Comment by dmcable** [comment]
Up to you. Either option will give similar results.

**Comment by EddieLv** [comment]
Hi, did you test those 2 ways? If you can tell us which way is better in deconvolution, I would be so appreciated:)
