### ISSUE TITLE
Some questions about input data

### ISSUE THREAD

**Issue by pumpkin-hat** [dmcable/spacexr#107]
Dear professor, 
    I'd like to use RCTD to infer cell types from spatial transcriptomics. I have questions about the input：
    1) Use all genes OR filter some? Can I just input the marker genes of each  cell  type?
    2) Do you change the threshold of nUMI when run Reference and SpatialRNA ?

Looking forward to your reply

**Comment by dmcable** [comment]
1. Typically, all genes are inputted and RCTD itself selects marker genes to use. There are parameters (for parameter documentation you can query: `?create.RCTD`) to adjust the gene selection cutoffs. If you want you can input your own selection of marker genes.
2. There is an option to set the `nUMI` threshold for each of `Reference` and `SpatialRNA` independently, but the default is 100 for each.

**Comment by pumpkin-hat** [comment]
> 1. Typically, all genes are inputted and RCTD itself selects marker genes to use. There are parameters (for parameter documentation you can query: `?create.RCTD`) to adjust the gene selection cutoffs. If you want you can input your own selection of marker genes.
> 2. There is an option to set the `nUMI` threshold for each of `Reference` and `SpatialRNA` independently, but the default is 100 for each.

I will try to use all genes as input.Thanks for your reply!

**Comment by madhavitippani** [comment]
How to input our own selection of marker genes. What is the option used in create.RCTD or run.RCTD. Also, what format should the marker genes be in.

**Comment by madhavitippani** [comment]
And for full mode where do we input the number of cells per spot info
