### ISSUE TITLE
intepretation and downstream analysis of RCTD weight in the output 

### ISSUE THREAD

**Issue by lengfei5** [dmcable/spacexr#108]
Hi there, 

We really love this package and are using it in our paper. 

I am wondering, in the output of RCTD, if the weight matrix (no-normalized to be fractions) can be interpreted in the absolute cell number sense, (meaning proportional to the cell number in each spot). 

Can we use that non-normalized weight matrix to do NMF/LDA to infer the cellular compartment, in the same way as cell2location  (https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html#Downstream-analysis) ?
 
Thanks.

Best,
Jingkui

**Comment by lengfei5** [comment]
Hi @dmcable ,
Thanks for such prompt answer, 
don't you think we can assume that the conversion factor of UMI per cell is roughly the same, as long as the spot is large enough to include couple of cells  ?

I hope I understood your concern.

Best,
Jingkui

**Comment by dmcable** [comment]
Sure, you can make that assumption.

Best,
Dylan

**Comment by lengfei5** [comment]
many thanks.

Best,
Jingkui
