### ISSUE TITLE
multiple samples used for reference

### ISSUE THREAD

**Issue by icanwinwyz** [dmcable/spacexr#109]
Dear spacexr authors,

Thanks for developing such a fantastic tool.

I have six 10X scRNA-seq samples and want to use them as the reference to deconvolute a 10X visium sample. Do I need to aggregate all six samples, correct batch effect by Harmony, and normalize them, then exact the expression matrix as the reference? or just simply merge all six raw expression matrices?

Joe

**Comment by dmcable** [comment]
Hi Joe,

Thank you! Either option works; those are both reasonable ideas, and it is based on your preference.

Best,
Dylan

**Comment by nwarnock** [comment]
Hi Dylan,

Amazing work developing these tools!

Following on from this discussion, I have two incomplete reference scRNA-seq datasets which I'd like to combine into a single complete reference for use with RCTD. You indicated above that this could be done either through merge or Harmony (or similar). I note in the manual that the counts in a reference object should be raw counts. Does this mean that any integration method should yield raw counts in the unified object?

Thanks,
Nick

**Comment by dmcable** [comment]
Not necessarily. RCTD also has an option to input the gene expression average matrix directly for each cell type. You can also input the counts as non-raw counts provided that the normalization occurred in linear space (as apposed to e.g. log space) given that RCTD will be taking averages. But there it is more likely with the second method that something would go wrong, so it's a better idea to compute the gene expression averages yourself, making sure that the values are in linear gene expression space (e.g. counts per million, counts per 1, counts pet N, etc).

**Comment by nwarnock** [comment]
Thanks for clarifying this - I appreciate you taking the time to outline these options.
