### ISSUE TITLE
find_sig_genes_individual: cell type Endo has not converged on any genes.

### ISSUE THREAD

**Issue by wang0430** [dmcable/spacexr#110]
myRCTD_identical <- run.CSIDE(myRCTD, X, barcodes, cell_types, gene_threshold = 5e-5, doublet_mode = F,                              cell_type_threshold = 10, fdr = 0.25) 
run.CSIDE.general: running CSIDE with cell types Endo, L6 CT run.CSIDE.general: configure params_to_test = 2,  1 2 

Error in find_sig_genes_individual (cell_type, cell_types, gene_fits, gene_list_type,  :    find_sig_genes_individual: cell type Endo has not converged on any genes. Consider removing this cell type from the model using the cell_types option.

 In addition: Warning message: In run.CSIDE.general(myRCTD, X1, X2, barcodes, cell_types, cell_type_threshold = cell_type_threshold,  :   run.CSIDE.general: some parameters are set to the CSIDE vignette values, which are intended for testing but not proper execution. For more accurate results, consider using the default parameters to this function.

**Comment by dmcable** [comment]
Please refer to the warning message above. You should use the default parameters, not the CSIDE vignette values.

**Comment by wang0430** [comment]
myRCTD_identical <- run.CSIDE(myRCTD, X, barcodes, cell_types, gene_threshold = 5e-5, doublet_mode = F,
+                               cell_type_threshold = 4, fdr = 0.25)
run.CSIDE.general: running CSIDE with cell types Astro, CR, Endo, L2_3 IT, L4, L5 IT, L5 PT, L6 CT, L6 IT, L6b, Lamp5, Macrophage, Meis2, NP, Oligo, Peri, Pvalb, Serpinf1, SMC, Sncg, Sst, Vip, VLMC
run.CSIDE.general: configure params_to_test = 2, 
1
2
**Error** in find_sig_genes_individual(cell_type, cell_types, gene_fits, gene_list_type,  : 
  find_sig_genes_individual: cell type Astro has not converged on any genes. Consider removing this cell type from the model using the cell_types

**Comment by wang0430** [comment]
I have an error at present, and I always suggest that the type of cells does not involve any genes, and I don't know why.

**Comment by wang0430** [comment]
I have an error at present, and I always suggest that the cell_type does not involve any genes, and I don't know why.

**Comment by dmcable** [comment]
You should raise `cell_type_threshold` to at least 50 or 100. The reason it does not converge on the cell type is because there are too few instances of the cell type. As described in the error, "Endo" and "Astro" cell types should be removed from the model.

**Comment by dmcable** [comment]
You should also check that you have sufficient number of genes in the RCTD object.

**Comment by wang0430** [comment]
Thank you for your reply. I just used the parameter test_genes_sig = f. There was no error. I checked the results first, and then tried the solution you said. Thank you very much for your positive reply. If you have any questions, please ask you if you have any questions.

**Comment by wang0430** [comment]
myRCTD1 <- run.CSIDE.nonparam(myRCTD, df = 15, cell_types = cell_types, gene_threshold = 5e-5, 
+                               doublet_mode = F,cell_type_threshold = 100, fdr = 0.01) 
**Error** in if (gene_threshold == 0.01 || fdr == 0.25 || cell_type_threshold ==  : 
  missing value where TRUE/FALSE needed

**Comment by wang0430** [comment]
Whenever I use the default parameter, there will always be errors

**Comment by dmcable** [comment]
The most recent error you posted is a legitimate issue. Can you please confirm you are using the current version by updating the package and checking if the error persists? If so, then please send me the `myRCTD` object and `cell_types` list so that I may reproduce the error.

**Comment by dmcable** [comment]
I wrote a more extensive reply for your case here: https://github.com/dmcable/spacexr/tree/master/documentation#frequently-asked-questions-faq-and-errors

**Comment by wang0430** [comment]
“”“”
3553
3554
3555
3556
Error in `[.data.frame`(sig_genes, abs(sig_genes$p_val < p_thresh) & abs(sig_genes$log_fc) >=  : 
  promise already under evaluation: recursive default argument reference or earlier problems?
“”“
I changed some parameters and showed that I had successfully run, but when I reached '3556', I displayed this error. I don't know why.Please help you see.

At the same time, when I modify the FDR, it will also display errors, but there is no problem with modifying other parameters.
"""
Error in if (gene_threshold == 0.01 || fdr == 0.25 || cell_type_threshold == :
missing value where TRUE/FALSE needed
"""

**Comment by wang0430** [comment]
“”“”
3553
3554
3555
3556
Error in [.data.frame(sig_genes, abs(sig_genes$p_val < p_thresh) & abs(sig_genes$log_fc) >= :
promise already under evaluation: recursive default argument reference or earlier problems?
“”“
I changed some parameters and showed that I had successfully run, but when I reached '3556', It displayed this error. I don't know why.

At the same time, when I modify the FDR, it will also display errors, although I have used the latest version, but there is no problem with modifying other parameters.
"""
Error in if (gene_threshold == 0.01 || fdr == 0.25 || cell_type_threshold == :
missing value where TRUE/FALSE needed
"""

**Comment by dmcable** [comment]
Please include the exact line of code used to produce each of the above errors.

Please send me the myRCTD object and cell_types list so that I may reproduce the errors.

**Comment by wang0430** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        When I modify the FDR, it will also display errors, although I have used the latest version, but there is no problem with modifying other parameters."""Error in if (gene_threshold == 0.01 || fdr == 0.25 || cell_type_threshold == :missing value where TRUE/FALSE needed"""
            
        
    
    
        Attachment is MyRCTD object.Cell-types list:  "L6 IT",  "L6 CT",  "Meis2",  "Astro",  "Pvalb",  "Oligo"   "L4",     "L5 IT",  "L2_3 IT".
        
    My code: {myRCTD1 <- run.CSIDE.regions(myRCTD, region_list, cell_types = cell_types, gene_threshold = 5e-5, cell_type_threshold = 100, fdr = 0.01, doublet_mode = F, weight_threshold = NULL)}
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Dylan ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/3/2022 00:27
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [dmcable/spacexr] find_sig_genes_individual: cell type Endo has not converged on any genes. (Issue #110)
        
      
    
  
  
I wrote a more extensive reply for your case here: https://github.com/dmcable/spacexr/tree/master/documentation#frequently-asked-questions-faq-and-errors

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>



   从 网易邮箱大师 发来的云附件                           myRCTD.zip        (55.5MB,2022年10月18日 13:38 到期)        下载
