### ISSUE TITLE
Can I use the results of other deconvolution methods as the input of CSIDE?

### ISSUE THREAD

**Issue by Smilenone** [dmcable/spacexr#111]
Is there any necessary that I can use the results of other deconvolution methods as the input of CSIDE?

**Comment by Smilenone** [comment]
Thanks for your help! I tried to use `import_weights` function,  and the weight had been normalized by `normalize_weights` in your package. However, there still maked an error: 
```
Error in import_weights(myRCTD, norm_weights) : 
  import_weights: weights must be normalized to have rows sum to 1.
```

Can you help?

**Comment by dmcable** [comment]
The requirement for normalized weights is that the following must be `FALSE`: `any(rowSums(weights) != 1)`.
