### ISSUE TITLE
Should I set the small weights to zero ?

### ISSUE THREAD

**Issue by lzygenomics** [dmcable/spacexr#112]
Hi~

Thanks for your fancy work ! I have a question about results: Due to the spot doesn't have that many cells, may I count those small weights in results as 0 ?

Best~

**Comment by dmcable** [comment]
If you are using full mode, there will be some noise in the weights. It would be reasonable to treat small weights below some threshold as essentially 0.

**Comment by lzygenomics** [comment]
Thank you for your quick reply! Really helpful~
