### ISSUE TITLE
Multi-sample differential expression by cell type ignoring spatial coordinates.

### ISSUE THREAD

**Issue by meaksu** [dmcable/spacexr#113]
Hi,
I've been trying to use your package and didn't see any vignettes on how to find differential expression for cell types by condition where you have multiple samples for each condition. I have 10 samples for case and 10 samples for control. What I did was, first create a puck object using the SpatialRNA function for all 20 samples using "use_fake_coords = TRUE", since I only care about the cell types and want to ignore spatial coordinates for now. I then run create.RTCD and run.RTCD on the puck object to get the cell types. Next, I created an explanatory variable by labeling all the cell barcodes that are control (pooled together) as 0 and the barcodes that are case (pooled together) as 1. Finally, I ran run.CSIDE.single on the myRTCD 20 sample object with cell types created above, using this explanatory variable. My questions are:

1. Is this the correct way to perform what I want to do, where I pool all samples together and create an arbitrary explanatory variable based on condition, and then use run.CSIDE.single?

2. If this is the correct way, and I use 0 to label control and 1 to label case, would a negative log Fold change indicate the cell type is downregulated in case as compared to control (i.e. which direction is the +/- sign in the logFC with respect to the two conditions)?

Thank you

**Comment by dmcable** [comment]
Both questions are correct, this is a reasonable way to perform this analysis. For an alternative method, see also: https://github.com/dmcable/spacexr/issues/100

**Comment by meaksu** [comment]
Thanks!
