### ISSUE TITLE
use RCTD with lists of cell type marker genes

### ISSUE THREAD

**Issue by linpei26** [dmcable/spacexr#114]
Hi Dylan!

I wish to know if it is possible to apply RCTD by using lists of cell types marker genes as Single-Cell Reference, without the count matrix?

Thanks!

**Comment by dmcable** [comment]
Hi, RCTD won't work with a list of marker genes, although you may subset the genes used to be marker genes. Also, for RCTD, you can input a matrix of gene averages for each cell type, rather than an entire single cell counts matrix.

Best,
Dylan

**Comment by linpei26** [comment]
"Also, for RCTD, you can input a matrix of gene averages for each cell type, rather than an entire single cell counts matrix."
- That's helpful.

Thank you Dylan!
Best,

Pei

**Comment by linpei26** [comment]
Hi Dylan!

When you suggested that "Also, for RCTD, you can input a matrix of gene averages for each cell type, rather than an entire single cell counts matrix.", do you mean a matrix of M rows for M genes and N columns for N cell type?
Each element [i,j] in this M x N matrix corresponding to the average expression of gene i in cell type j.


Am I right?
Thanks!

Pei

**Comment by dmcable** [comment]
Yes, that's correct.

**Comment by linpei26** [comment]
Thanks.
I have tried this strategy as I do not have the full count matrix for single cell expression.
However, I found err msg as:

"Error in process_cell_type_info(reference, cell_type_names = cell_type_names,  : 
  process_cell_type_info error: need a minimum of 25 cells for each cell type in the reference"

Does it suggest that one cell type should have >= 25 columns in the counts matrix of the reference object.

Thanks!

Pei

**Comment by linpei26** [comment]
Dose it work by setting CELL_MIN_INSTANCE = 1 when running create.RCTD?
Thanks.

**Comment by dmcable** [comment]
That is one option (also set `require_int = FALSE`).

The other option is to pass in the `cell_type_profiles` argument into the `create.RCTD` function (latest version), rather than the `Reference` object (passed in a NULL), where `cell_type_profiles` is the genes by cell types matrix, with rownames and colnames. When using this option, it is the user's responsibility to ensure this matrix is formatted correctly.
