### ISSUE TITLE
unused argument (cell_type_info = cell_type_info)

### ISSUE THREAD

**Issue by Jluo21** [dmcable/spacexr#117]
Hi Dylan,
I installed you most recent version of this package and got the following error. I did no see this error when I run this with the version installed last month. Could you please help to check? Thanks!

create.RCTD.replicates: creating RCTD for replicate 1
Error in create.RCTD(spatialRNA.replicates[[i]], reference, max_cores = max_cores,  : 
  unused argument (cell_type_info = cell_type_info)
Calls: create.RCTD.replicates

**Comment by dmcable** [comment]
Thank you, this bug should now be fixed.

**Comment by Jluo21** [comment]
Hi Dylan，

Thanks.
I just have another question. I got the population de results with all
genes having negative lfc_est values when comparing two areas. Do you know
why this happened?

Best,
Jialie

**Comment by Jluo21** [comment]
I'm sorry that I can't send you my client's data. Do you have any idea how
could that happen?

**Comment by dmcable** [comment]
Email me at ***@***.***
