### ISSUE TITLE
Bug in import_weights

### ISSUE THREAD

**Issue by abayegan** [dmcable/spacexr#118]
The import_weights returns error: 

`Error in import_weights(rctd, decon) : 
  import_weights: weights must be normalized to have rows sum to 1.`

This is due to R issues with numeric comparison using '=='. Using `all.equal` or allowing a small epsilon difference in line `if(any(rowSums(weights) != 1))` of import_weights can solve the problem.

**Comment by dmcable** [comment]
Thanks, just pushed a fix to this issue.
