### ISSUE TITLE
Population-level RCTD and C-SIDE vignette

### ISSUE THREAD

**Issue by Jluo21** [dmcable/spacexr#120]
Hi Dylan, 
I got the following error message when try to run the vignette: [Population-level RCTD and C-SIDE](https://raw.githack.com/dmcable/spacexr/master/vignettes/replicates.html).
create.RCTD.replicates: creating RCTD for replicate 1
create.RCTD: getting regression differentially expressed genes: 
Error in get_de_genes(cell_type_info$info, puck.original, fc_thresh = config$fc_cutoff_reg,  : 
  get_de_genes: Error: 0 common genes between SpatialRNA and Reference objects. Please check for gene list nonempty intersection.

**Comment by dmcable** [comment]
Bug is fixed now, thanks for catching this.

**Comment by Jluo21** [comment]
Can you check again? I still got the same error.

**Comment by dmcable** [comment]
What version of the package are you using?

**Comment by Jluo21** [comment]
I installed today from GitHub. I think it is the latest version.

**Comment by Jluo21** [comment]
It works now. Thanks.

**Comment by Jluo21** [comment]
I got the following error when I ran cside of the vignette:
run.CSIDE.replicates: running CSIDE for replicate 1
Warning: run.CSIDE.general: removing the following cell types due to insufficient counts per region. Consider lowering cell_type_threshold or proceeding with removed cell types. Cell types: 18, 
run.CSIDE.general: running CSIDE with cell types 10
run.CSIDE.general: configure params_to_test = 2, 
filter_genes: filtering genes based on threshold = 0.01
Error in base::rowSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions

**Comment by dmcable** [comment]
Thanks for bringing this to my attention. This error has now been fixed, and please note that the vignette code has also changed.
