### ISSUE TITLE
reference downsample

### ISSUE THREAD

**Issue by Jluo21** [dmcable/spacexr#121]
Hi Dylan, 
I have a huge myRCTD.reps object because the down sample of reference did not work in run.RCTD.replicates(). down sample will only run if the cell_type_profiles object is null, however it is not null in this case.

![image](https://user-images.githubusercontent.com/95539498/200183409-77930e1e-f4c7-4f11-939c-b75dbcbd4f71.png)

![image](https://user-images.githubusercontent.com/95539498/200183540-dd942d8b-57ab-49ef-afe1-c60e133ff7f3.png)

**Comment by dmcable** [comment]
Thanks, I've changed this function so that the down-sampling of the reference is available in all cases, which addresses your case.
