### ISSUE TITLE
Batch correction of multiple Visium samples 

### ISSUE THREAD

**Issue by moutazhelal** [dmcable/spacexr#122]
Dear Authors,

I would like to deconvolute multiple Visium samples and to compare cell abundance between different samples. Those samples were collected from different tissues and time points.should I batch correct  the concatenated matricies? what tool so you recommend me using for batch correction.

Thank you very much for your help,
Best,
Moutaz

**Comment by dmcable** [comment]
You can run RCTD directly on the raw data, separately for each sample, because RCTD includes its own platform effect (i.e. batch) normalization step.
