### ISSUE TITLE
Inquiry about import_weights function

### ISSUE THREAD

**Issue by pekjoonwu** [dmcable/spacexr#123]
Hey Dylan,

Thanks for developing this amazing tool!

I have a question about the 'import_weights' function. It seems like this function can only apply to the RCTD object with 'full' mode if I understand correctly since the function only alters the 'weight' parameter within the RCTD object? If this is the case, then for the single cell level spatial data, how should I import the known cell type labels into the object for each cell?

Thanks,
Peijun

**Comment by dmcable** [comment]
Yes it is a matrix of cell type proportions. Single cells correspond to one
cell type having proportion 1, the rest proportion 0.

Dylan

**Comment by pekjoonwu** [comment]
Maybe my question was not clear enough. Its seems like the import_weights function is only assigning the cell type proportion matrix to the 'weights' parameter. 

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/43768681/203868129-4000ccdf-4011-43e8-9abf-ee4aadc1b917.png">

However, the run.CSIDE.nonparam which uses 'doublet' mode as default is only using 'weights_doublet' parameter in the inference if I understand correctly. Besides, I looked at the results from two objects where one of them ran without import_weights function and they looked pretty much the same (But the binary matrix of cell type proportions is very different from the previous RCTD output).

Please let me know if I misunderstood the vignettes or the code.

Thanks!

**Comment by dmcable** [comment]
Doublet mode is a specific way of storing the weights, but there is no
reason to use it outside of RCTD. Storing the weights as such in full mode
will produce equivalent results. C-SIDE can be run in full mode.

**Comment by pekjoonwu** [comment]
Do you mean I can still use full mode for the single cell level spatial data when running RCTD and CSIDE and I just need to import the binary cell type identities matrix using 'import_weights' function before running CSIDE?

Thanks!

**Comment by dmcable** [comment]
Yes
