### ISSUE TITLE
multiple explanatory variables

### ISSUE THREAD

**Issue by Jluo21** [dmcable/spacexr#125]
Hi Dylan,
I am trying to run cside using multiple explanatory variables (I have two now, one is type with two levles: CT, RCV, the other one is subject_id with has 6 levels). The X I created is like this:
![image](https://user-images.githubusercontent.com/95539498/207691608-33fd7862-02b0-4434-ba9f-ba26ce5013cf.png)
However, I got an error when run the following code:
![image](https://user-images.githubusercontent.com/95539498/207692204-1cbfd698-88a5-4d7b-9faf-04ee52c83872.png)
![image](https://user-images.githubusercontent.com/95539498/207692392-71721a1c-b04b-4b96-aff5-d85cf6123c3a.png)

Could you please help to check what is the problem?
Thanks!

**Comment by dmcable** [comment]
Hi, the columns of X must be linearly independent (as in linear
regression). I believe in your case that since every element has a
subject_id = 1, the intercept term is redundant and should be removed.

Dylan
