### ISSUE TITLE
Possible to  use pseudobulk as reference?

### ISSUE THREAD

**Issue by agelber-ucsd** [dmcable/spacexr#126]
Is it possible to use pseudobulk from an annotated single cell dataset to create a reference? I tried setting CELL_MIN_INSTANCE to 1 but got "Error in array(STATS, dims[perm]) : 'dims' cannot be of length 0"

Does the algorithm use the variance in the reference in some way?

**Comment by dmcable** [comment]
Yes, see: https://github.com/dmcable/spacexr/issues/114#issuecomment-1297595881

Variance is not used.

**Comment by agelber-ucsd** [comment]
Thanks!
