### ISSUE TITLE
Error in run.CSIDE

### ISSUE THREAD

**Issue by Jluo21** [dmcable/spacexr#128]
Hi Dylan,

I encountered the following error when run the `run.CSIDE` function. Do you know what is the problem?

loaded spacexr and set parent environment
Loading required package: Rcpp
Loading required package: RcppZiggurat
Error in { : task 1 failed - "subscript out of bounds"

**Comment by dmcable** [comment]
Can you please rerun with 1 core, post the error message, and then also
post/email your data and the code that was run? Thanks.

**Comment by Jluo21** [comment]
Thanks for your suggestions. I used 1 core and get the following error:

![image](https://user-images.githubusercontent.com/95539498/208937897-53a458a9-cdbc-4fda-a907-37d02aebe98c.png)

**Comment by dmcable** [comment]
I would need your data to debug further.

**Comment by Jluo21** [comment]
I am sorry that I am not authorized to share the data here.

When I changed the cell type, there is no error when running with 1 core. The Warning is still there:
![image](https://user-images.githubusercontent.com/95539498/208959803-43f78333-98cb-49fb-ad65-c39e699b41cf.png)


When running with multiple cores for the cell type (succeeded when using 1 core), I still have the error:
 Error in { : task 1 failed - "subscript out of bounds"

Usually I would like to test a list of cell types. Could you have the program test each cell type and remove cell types that are not converged on any genes before running CSIDE?

**Comment by dmcable** [comment]
The options are to email me the data privately, or you can subsample the data to create a toy dataset and share that.
