### ISSUE TITLE
Quick question on using C-side for finding DEGs between samples

### ISSUE THREAD

**Issue by Lesdormis** [dmcable/spacexr#129]
Thanks for developing this amazing tool. I have a quick question on how to properly use C-side as a DEG method on our Slide-seq data like disease vs control.
Based on the tutorial, we need to first run RCTD by using Spatial Transcriptomic data and single-cell RNA data as reference. What if I don't have single-cell RNA-seq data? Can I just use the ST as a reference, and should I worry about setting different parameters along the process?

Thanks!

**Comment by dmcable** [comment]
If you have an cell type-annotated single-cell spatial transcriptomics dataset, then you can use that as a reference.

If you don't have an annotated single-cell RNA-seq reference, then it is still possible to run C-SIDE if you obtain cell type proportions another way. To do so, you should run `create.RCTD`, then `import_weights` (to import the cell type proportions), and then C-SIDE. 

Best,
Dylan
