### ISSUE TITLE
could not find function "solveIRWLS.weights"

### ISSUE THREAD

**Issue by lDesiree** [dmcable/spacexr#130]
I am trying to run the vignette https://github.com/dmcable/spacexr/blob/master/vignettes/visium_multi.Rmd and get the following error:

```
myRCTD <- run.RCTD(myRCTD, doublet_mode = 'multi')
fitBulk: decomposing bulk
chooseSigma: using initial Q_mat with sigma =  1
starting worker pid=28143 on localhost:11582 at 03:56:48.899
starting worker pid=28158 on localhost:11582 at 03:56:49.757
Loading required package: spacexr
Loading required package: spacexr
Error in { : 
  task 1 failed - "could not find function "solveIRWLS.weights""
```
I also tried to run the function in the "full" and "doublet" mode and installed the package on two independent machines (Linux and Mac). but I always get the above error message.

**Comment by dmcable** [comment]
What version of the software are you running? I can't seem to reproduce this error.
