### ISSUE TITLE
Question regarding CSIDE with complex experimental design

### ISSUE THREAD

**Issue by Dillon214** [dmcable/spacexr#133]
Hello spacexr developers,

I have a question regarding CSIDE, and how it can be applied to multiple visium slides with a complex experimental design. 
Looking at the vignette labelled 'Applying CSIDE to Spatial Transcriptomics Data: Differential Expression with Multiple Experimental Replicates', it seems like CSIDE can handle covariates that are likely to differentiate spaces within a given slide, or set of experimental replicate slides. In the vignette, the example is region. However, I was wondering if CSIDE could handle covariates that are different between samples alltogether? Say I had replicate 3 slides of one experimental condition, such as control, and 3 of another, such as disease, and I wanted to perform DE between a given cell type between control and disease? 
I have not read about CSIDE extensively, I'm simply interested in the tool, so I apologize of this question is an obvious one. 

-Dillon

**Comment by Dillon214** [comment]
There are previous answers to this question I didn't notics

**Comment by dmcable** [comment]
Hi Dillon,

I just responded to your other issue with the following info: I've added a new feature for meta regression, which can account for covariates such as time and case/control, as well as test along these covariates. Please see the meta-regression section of this vignette: https://raw.githack.com/dmcable/spacexr/master/vignettes/replicates.html

Best,
Dylan
