### ISSUE TITLE
Question about normalizing/workflow for many slides in a complex experiment

### ISSUE THREAD

**Issue by Dillon214** [dmcable/spacexr#134]
This question references both of the below issues: 
Batch correction of multiple Visium samples #122
Multi-sample differential expression by cell type ignoring spatial coordinates. #113

Hello spacexr devs,

I am interested in using spacexr's RCTD/CSIDE to perform DE tests on a few specific cell types in the context of a complex experimental design. Relevant covariates include case/control, tissue, and timepoint. Also, the data is Visium. 
I think implementing a workflow similar to the one suggested in closed issue #113 is most apt for my study goals as they stand now, however I have a question regarding how to normalize my samples. I believe #113 performs RCTD on all samples in one puck, but issue #122 instead suggests normalizing by first performing RCTD on all samples individually for the purposes of batch correction. 

I believe that RCTD could be run on all the samples aggregated together due to the platform effect normalization mentioned in #113. and in light of the response to #122 this would make sense, but I wanted to ask the developers themselves. 

Thank you very much for developing this great tool, and thank you for the support

**Comment by dmcable** [comment]
Hi Dillon,

Thanks for this and your previous question of adding covariates across samples. I think it's an important and common scenario, and I've added a new feature for meta regression, which can account for covariates such as time and case/control, as well as test along these covariates. Please see the meta-regression section of this vignette: https://raw.githack.com/dmcable/spacexr/master/vignettes/replicates.html

Best,
Dylan

**Comment by Dillon214** [comment]
Hi Dylan,

Thank you so much for the swift support! I'll give the new feature a shot as soon as I start deconvolution, and give you an update on how it goes. I'll be closing this issue for now, but I'll be in contact again. 

Thanks again,
Dillon

**Comment by Dillon214** [comment]
Hi @dmcable, 

I have a question about the solution you posted to the issue I had. I checked out the vignette you linked and, while I think the functionality of population inference: meta regression is very useful, I don't think it addresses my question. The way I see it, meta regression seems more aimed at first performing cell type-specific DE on each sample based on some shared covariate, such as spatial position, then afterwards testing for differences in DE results based on sample condition. I am aiming for something a little more simple at the moment: performing cell type-specific DE between samples of different conditions, a la issue #113, preferably with an arbitrarily complex experimental design (as my original question mentioned, I have at least a 3 level design). 
So, while I think meta-regression is a great tool and one I would like to use later on in my analsis, I don't think it is right for my issues as they stand. Do you still stand by the advice you provided in issue #113, and do you think I could ammend said workflow to handle a 3-level experimental design? In a perfect world, I would like to test for differences in a specific cell type's response to disease while controlling for timepoint. Your support and advice are greatly appreciated.  

Also, if I am misinterpreting the function of meta-regression, please don't hesitate to let me know. I have yet to give it a proper test, so I might be mistaken. 

Sincerely,
Dillon Brownell
