### ISSUE TITLE
Installation Issue for MacBook with the newest version 2.2.0

### ISSUE THREAD

**Issue by wxy929** [dmcable/spacexr#136]
Dear Dylan,

Upon your suggestion, I'm trying to update my package spacexr to the newest version. I deleted the package first, but when I tried to reinstall it, the installation code "devtools::install_github("dmcable/spacexr", build_vignettes = FALSE)" doesn't works for my MacBook with system MacOS Ventura 13.1. The error message is shown as follows.

Downloading GitHub repo dmcable/spacexr@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/dmcable/spacexr/tarball/HEAD' failed

I tried this on another laptop with Windows 10 system, and it did work. So I'm not sure why this happened. Any comments will be appreciated gratefully. Thanks a lot in advance for your help.

Best,
Xinyue Wang

**Comment by dmcable** [comment]
It could be due to timing out of the `install_github` function. I would try first running `options(timeout=9999999)`.

See: https://stackoverflow.com/questions/65421798/devtoolsinstall-github-failing-in-r4-0-03

Best,
Dylan

**Comment by wxy929** [comment]
This works! Thank you very much.

Best,
Xinyue
