### ISSUE TITLE
No output for meta regression vignette

### ISSUE THREAD

**Issue by Jluo21** [dmcable/spacexr#137]
Hi Dylan,

I just tried running the vignette of meta regression. However, there is no results after running the codes. Could you please help to check?
![image](https://user-images.githubusercontent.com/95539498/217549910-593885aa-f86b-4eaa-a8c1-aa20b4d70454.png)
Thanks!

**Comment by dmcable** [comment]
thank you, and sorry for the late response. this issue has been fixed. please try updating the package.
