### ISSUE TITLE
Installing at Rstudio2022.12.0 isn't working

### ISSUE THREAD

**Issue by MovmntR** [dmcable/spacexr#138]
Thanks for this awesome tool.
However, the installing command isn't working now for my laptop.
What should I check or reinstall?

> devtools::install_github("dmcable/spacexr", build_vignettes = FALSE)
Downloading GitHub repo dmcable/spacexr@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/dmcable/spacexr/tarball/HEAD' failed

**Comment by darkcircle** [comment]
same here. and it also occurs in R shell.

**Comment by MostBeef** [comment]
Same problem. I worked around by downloading and installing from file using devtools::install_local

**Comment by gong-dennis** [comment]
Setting `options(timeout = 600000000)` worked for me and others. In some cases I think the download times out, causing the error. 
See https://github.com/dmcable/spacexr/issues/136#issuecomment-1421761020

**Comment by dmcable** [comment]
Yes, I agree with the above to avoid timeout error. I am adding this to the official installation instructions.
