### ISSUE TITLE
Deconvolution using highly correlated subpopulations in reference single cell dataset

### ISSUE THREAD

**Issue by aelhossiny** [dmcable/spacexr#139]
Hi, Thanks you for this amazing package! 

I was wondering how granular can I get when I annotate my reference single cell dataset? In other words, how stable the results would be if I have highly correlated subpopulations in my reference where only few genes differentiate between them but they have high correlation in their expression profile (e.g. Effector CD8 T-cells and Exhausted CD8 T-cells)?

Is there a recommended cut-off or metric that I can use to determine to what extent can I subcluster my reference? or should I stick to the main annotations (e.g. epithelial, fibroblast, T-Cells,... etc) without getting to much granular?

Thanks!

**Comment by dmcable** [comment]
Hi @aelhossiny ,

I have written a reply to this question in the F.A.Q. section of  https://github.com/dmcable/spacexr/tree/master/documentation, under the title of "Subtypes with RCTD: how do I create cell type assignments with RCTD for precise subtypes?" I hope you find this response helpful.

Dylan

**Comment by bai1111111111** [comment]
Hi,  @Dylan!
I have read the documentation about “Subtypes with RCTD: how do I create cell type assignments with RCTD for precise subtypes?” You have mentioned “Note that this discussion pertains to doublet mode of RCTD” in the documentation. I wonder if the parameter “class_df” can also be used in “full mode” and “multi mode”?
Thanks!

**Comment by dmcable** [comment]
Hi, `class_df` only pertains to doublet mode. If you want subtypes in full mode, you can just pass in all subtypes. Currently, there we have not implemented this for multi mode.

Dylan
