### ISSUE TITLE
Deconvolution with integrated scRNA data when there is no paired data

### ISSUE THREAD

**Issue by RYY0722** [dmcable/spacexr#143]
Hi there! Thanks a lot for the great work!
I am currently working on a dataset where some samples do not have paired sc/snRNA data. So I am wondering how can I transform the problem to use RCTD since it seems that the input to the algorithm should be un-normalized counts. However, after integrating the samples using the method by seurat [here](https://satijalab.org/seurat/articles/integration_introduction.html#introduction-to-scrna-seq-integration-1), I got normalized data and cannot access some un-normalized counts equivalent. For another thing, the deconvolution results of RCTD is far more robust than other methods. Thus, I really want to continue to use it for the remaining samples without paired scRNA data. Would you please give me some suggestions regarding this? Thank you very much!

**Comment by dmcable** [comment]
Sorry, I'm not sure I understand your question. For the sc/snRNA-seq reference, you can just use a single reference for all your samples. You don't need to create a new reference for each sample. Please let me know if there is anything else I can help answer.

Best,
Dylan

**Comment by RYY0722** [comment]
Thanks a lot for your reply! Because not all my ST samples have paired sc/snRNA-seq data. But I have 15 sc/snRNA-seq data of similar tissues. Therefore, I wish to utilize an integration of these single cell data to deconvolute the ST samples that do not have paired single cell data. Can I still utilize RCTD in this case? I tried using counts after the SCTransform as the input count matrix.

**Comment by dmcable** [comment]
Yes. Just create a spacexr Reference object using the raw counts from the sc/snRNA-seq datasets. It is fine if it is similar samples but not the exact same tissue. For passing in the data for RCTD, you should always use raw counts and shouldn't use SCTransform or any kind of transformation.

Best,
Dylan

**Comment by dmcable** [comment]
Dear Yuyan,

You have two options here. First, you can try to concatenate both the references without any normalization, and see if that works. Second, you may apply a normalization method first and then pass in the cell type means in the RCTD object. Please note that the units of the cell type means are normalized expression in linear space (counts per 1).

Best,
Dylan
