### ISSUE TITLE
Combining primary and liver Mets 

### ISSUE THREAD

**Issue by spatialbiology1** [dmcable/spacexr#146]
I plan to carry out deconvolution of primary colon and liver metastasis. I would appreciate any guidance . Should I first analyze each sample individually or can analyze all samples from various patients together. I’ll appreciate the input 
Many thanks 
Zin

**Comment by dmcable** [comment]
For the RCTD method, the results will be equivalent whether run on samples individually or jointly. If you would like to run it jointly, we recommend checking out our multi-replicates vignette here: https://github.com/dmcable/spacexr/tree/master/vignettes#batch-processing-of-multiple-experimental-replicates--population-level-de-inference

Best,
Dylan
