### ISSUE TITLE
Input non-integer (corrected/cleaned) counts for RCTD

### ISSUE THREAD

**Issue by cf98** [dmcable/spacexr#147]
Hi Developers,

Thanks for developing such a great tool for deconvolution.

I am analyzing 10X Visium data, and I have used a tool called SpotClean that corrected diffusion, and it makes sense biologically. However, the counts are not integer anymore. When I try to use this as input to RCTD, it won't allow me to run deconvolution, as the counts are non integer.

Is is possible to allow input of non integer Visium counts?

Thanks!

**Comment by dmcable** [comment]
Hi, RCTD only runs on raw counts. However, if their is diffusion, this should be tolerated, as it will be treated as cell type mixtures, which is handled by RCTD.

Dylan

**Comment by cf98** [comment]
> Hi, RCTD only runs on raw counts. However, if their is diffusion, this should be tolerated, as it will be treated as cell type mixtures, which is handled by RCTD.
> 
> Dylan

Thank you Dylan!
