### ISSUE TITLE
Is it possible to use non-integer gene count (e.g. normalized expression) as input

### ISSUE THREAD

**Issue by kangjiajinlong** [dmcable/spacexr#148]
Hi @dmcable,

The RCTD paper mentions that RCTD uses raw gene count as input. I tried to use a reference seurat object with @count slot having non-integers entries and RCTD gave me an error saying that the check_counts() failed. I wonder if using non-integer gene count (e.g. normalized expression) as input is OK. If it is technically OK to do this, is there any option I can specify to bypass the check_counts()? Also is there some biological pitfalls for using normalized expression?

Thanks,
Jack

**Comment by dmcable** [comment]
Hi @kangjiajinlong ,

Apologies for the late reply. RCTD requires raw gene counts because it directly models the data using a Poisson distribution. RCTD performs it's own normalization. I recommend recovering the raw gene counts from wherever you obtained your data.

Best,
Dylan
