### ISSUE TITLE
RCTD error

### ISSUE THREAD

**Issue by wang0430** [dmcable/spacexr#149]
Hello, thank you very much for developing such a great tool
When I was using RCTD recently, I had a problem. My spatial transcriptome data is 2268 spots, and the constructed punk is also 2268 spots, but when I run RCTD to get the result, there are only 2226 spots. What is going on? How can I solve it, because if the two spots are different, some of my follow-up analyzes cannot be carried out.
![1681819044750](https://user-images.githubusercontent.com/112233361/232770282-e2ed3669-f305-4fbd-842a-089e629d63ef.png)
![1681819055944](https://user-images.githubusercontent.com/112233361/232770308-bd1390ce-4718-4b8a-881e-64eecb30f396.png)
![1681819072795](https://user-images.githubusercontent.com/112233361/232770323-9f4ddffc-fd9f-4fef-819a-4cc6f5c4a44d.png)

**Comment by dmcable** [comment]
Most likely as @gsmuir said, spots with less than 100 nUMI were removed. If you would like to match up the spots in the two list, I recommend using the barcode names which should be consistent.

Best,
Dylan
