### ISSUE TITLE
Could not find function "merge.RCTD.objects"

### ISSUE THREAD

**Issue by ivykos** [dmcable/spacexr#150]
Hi there

Just have a quick question that I hope can be addressed. I have multiple RCTD objects that I want to run population-level DE on with CSIDE, but when I try to use the merge.RCTD.objects function, it returns the could not find function error. Spacexr is loaded, and I can even read the documentation with `?merge.RCTD.objects`, but I just can't use it in my code. Any idea what might be the reason for this?

Thanks!

**Comment by dmcable** [comment]
Hi,

Apologies for the late response. The function is `merge_RCTD_objects`. If you could point me to where you saw `merge.RCTD.objects` in the documentation, I can fix the typo.

Best,
Dylan

**Comment by dmcable** [comment]
The manual is from version 2.0.0 so it is out of data. I can work on updating the manual.
