### ISSUE TITLE
Assigning cell types to each barcode

### ISSUE THREAD

**Issue by deconvolute** [dmcable/spacexr#151]
We have run RCTD on 10X visium in multimode, because it is recommended for visium, as each spot contains around 10 cells. Is there a way we can assign a single cell type to each barcode?

**Comment by dmcable** [comment]
Multi mode assigns multiple cell types per location. You can determine the maximum cell type per barcode by looking at the cell type proportions and choosing the maximum one.

Best,
Dylan
