### ISSUE TITLE
RCTD on multiple tissue sections in one Visium capture area

### ISSUE THREAD

**Issue by sbaghai** [dmcable/spacexr#152]
Hi @dmcable, many thanks for the handy tool and the user-friendly vignettes!

I’m running RCTD on Visium data (with a matching scRNAseq reference), and in each capture area I have 3-4 well separated small tissue sections (think scattered islands).
I tried RCTD (full mode) both on each whole capture area (i.e., for the spaceranger-filtered spots) and on each tissue section as a stand alone (subsetting the matching spots). Results somewhat differ but I don’t see a clear pattern in the differences, nor an improvement in either (other than few samples with low counts/UMIs being dropped because of little DEG overlap with the reference - "get_de_genes: At least 90% of genes do not match between the SpatialRNA and Reference objects."), so I would really appreciate a word of advice from you, or what to consider when making either choice.
I think this issue https://github.com/dmcable/spacexr/issues/106#issue-1389473714 was similar (although they speak of slides and not capture areas - where for me 1 slide = 2-4 capture areas, depending on the type), but I was hoping for more insight from you.

Thanks a lot!

**Comment by dmcable** [comment]
I would recommend looking more into the issue that you mentioned "get_de_genes: At least 90% of genes do not match between the SpatialRNA and Reference object". This is commonly caused by differences in naming conventions between the two datasets. In particular, I would list out the genes in the two datasets and look for reasons that genes in the SpatialRNA dataset do not appear in the Reference dataset.

Best,
Dylan

**Comment by sbaghai** [comment]
Hi Dylan, thanks for your suggestion!
I get that error with RCTD only if I run it on a given subset of spots (belonging to a tissue section with lower counts compared to the other sections on the same capture area).
The whole capture area, as well as subsets of it with high counts, get decomposed fine.
Overall I have >18K gene symbols in common between the reference and the spatial objects (the Visium experiment uses 10x [probe set ](https://support.10xgenomics.com/spatial-gene-expression-ffpe/probe-sets/Visium-Mouse-Transcriptome-Probe-Set-v1-0-mm10-2020-A) so it's not the full transcriptome, but should be representative enough).
~1200 gene symbols from the probe set also do not match the single cell reference, due to different aliases possibly, but these genes account for less than 1% of the total counts in the Visium (in 44 spots, for a median of 14 counts in those).
So I don't think that should be the main issue, but rather the lower UMI and gene detection for some sections.

In the end I chose to run RCTD on the whole capture area, expecting that even the tissue sections in it with lower counts would help inform a better platform effect normalization for the Visium. Do you see any fault in this?
I can consider myself satisied I think.
Thanks again!
Simo

**Comment by dmcable** [comment]
Got it. It is still unexpected that if you subset the pixels that you would run into the error of 90% of genes not matching. It could be worth debugging this further. If you provide the data / code then I can debug.

As for running on a larger region, that is completely fine, the results for individual pixels should be valid regardless of the region selected. Hope this helps.

Best,
Dylan

**Comment by nasimbio** [comment]
Hello,
I see this case is closed but I am facing the same issue for RCTD deconvolution of visium HD data. The visium HD has 18,085 number of genes and single cell ref has 42,496. They overlap for 17,201 genes.  
The error: Error in get_de_genes(cell_type_info$info, puck.original, fc_thresh = config$fc_cutoff_reg,  : 
  get_de_genes: At least 90% of genes do not match between the SpatialRNA and Reference objects.
I reduced the size of both to the common genes but didn't solve the issue. I'd appreciate if you help with this issue
