### ISSUE TITLE
RCTD generate NAs

### ISSUE THREAD

**Issue by ayusyarif** [dmcable/spacexr#155]
Dear RCTD Team,

I have analyzed my Visium data and generated deconvolution result using scRNA-seq reference. However, I noticed that 144 spots are being assigned as NAs. I am unsure where the NAs came from and what they mean. 

Would it be like undetermined spots where RCTD cannot assign any particular cell types?

Best Regards,
Ayu

**Comment by dmcable** [comment]
Dear Ayu,

Apologies for the late response. Generating NAs is definitely unexpected behavior. Can you please post more information so we can debug this issue including the RCTD object after RCTD was run? Thank you.

Best,
Dylan
