### ISSUE TITLE
a single-nucleus RNA-seq cerebellum dataset in the simulation

### ISSUE THREAD

**Issue by pekjoonwu** [dmcable/spacexr#157]
Hi Dylan,

I am trying to reproduce the simulation results in the CSIDE paper.

It seems like I cannot find the sn-RNAseq dataset in this repository https://singlecell.broadinstitute.org/single_cell/study/SCP1663/cell-type-specific-inference-of-differential-expression-in-spatial-transcriptomics even though it's in the readme.csv file.

I also tried to use the file 'scRefSubsampled1000_cerebellum_singlenucleus.RDS' in this repository https://singlecell.broadinstitute.org/single_cell/study/SCP948/robust-decomposition-of-cell-type-mixtures-in-spatial-transcriptomics#/ but I encountered the errors when I ran the script in the 'AnalysisCSIDE' folder. (The errors occurred when I tried to access some attributes in the Seurat object)

Do you mind providing the reference.rds in the command 'readRDS("../../../spacexr/data/Reference/10xCer/reference.rds")'.

Thank you so much!

Best,
Peijun

**Comment by dmcable** [comment]
Please check out our Dropbox repos:
RCTD study: https://www.dropbox.com/sh/6klgiz1f9rimzqb/AAA2PrAgPfgPFz4yNDBPEWqYa?dl=0
CSIDE study: https://www.dropbox.com/sh/one199micojkdrz/AAAhHFD-lu5IIIV3Y76tl9KYa?dl=0

Best,
Dylan
