### ISSUE TITLE
What does it mean to have "reject" in myRCTD@results$results_df$spot_class when using run.RCTD(doublet_mode = 'doublet')

### ISSUE THREAD

**Issue by estellad** [dmcable/spacexr#158]
Hi there,

Thank you for the great package! I have a question about the results when running RCTD with doublet mode.
In your documentation you mentioned: “reject” (no prediction given for pixel). Typically, reject pixels should not be used". Is there any reason why some pixels has no prediction? For example, more than 2 cells are detected for the "reject" pixels, so doublet mode is not suitable? This was not specified in the algorithm section of the RCTD paper. 

Thank you!
Estella

**Comment by dmcable** [comment]
Hi Estella,

Thank you for your question. The `reject` pixels are defined as pixels where there is not enough information to distinguish between the different potential cell types appearing on a pixel. For example, if there are two similar cell types that cannot be distinguished to a sufficient level of certainty. It does not necessarily mean that there are more than 2 cell types present. Rather, there is not enough or conflicting information.

Best,
Dylan
