### ISSUE TITLE
RNA normalisation before deconvolution

### ISSUE THREAD

**Issue by ayusyarif** [dmcable/spacexr#159]
Dear RCTD developer,

I encountered an issue with my deconvolution results. Using the Visium 10X platform, I observed that macrophages and B cells were the two most abundant populations, with an average proportion of 0.5 - 0.9. This result seems counterintuitive to what we have seen in the immunofluorescence or single-cell RNA seq. 

Is it due to the non-normalized count I used as an input for running RCTD? I came across an article from  Monaco, 2019 (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6367568/) stating that mRNA abundance and, thus, mRNA count could be influenced by cell size and metabolic activity. Could the size of the macrophage explain the observed proportion in a given spot?

Best Regards,
Ayu Hutami

**Comment by ayusyarif** [comment]
Hi Dylan,

Thank you for your explanation.
How do we do the scaling by the amount of mRNA from scRNA?

Regarding the gene set, I could not find any way to get the gene sets that
RCTD used for deconvolution analysis. Is there any function to retrieve
them? How can I select and filter gene signatures?
The tutorial at least did not show how to preselect the gene signatures in
order to tweak them.

Best regards,
Ayu

**Comment by dmcable** [comment]
Dear Ayu,

To convert from mRNA counts to cells, you can divide by the number of mRNA per cell of each cell type which can be estimated from a scRNA-seq dataset.

The function `get_de_genes` in RCTD is used to filter genes. There are a couple of parameters (input into `create.RCTD`) that you can play around with, including the expression level and the log-fold-change. You can also input your own genes using a method of your choice to select genes.

Best,
Dylan
