### ISSUE TITLE
SpatialRNA with 'require_int = F'

### ISSUE THREAD

**Issue by parkjooyoung99** [dmcable/spacexr#161]
Dear developer, 

I am currently using spacexr on 'raw spatial data' and 'spot cleaned spatial data with Spotclean R package'. 
The latter data have modified gene expression and is not integer. In this case, is it okay to use require_int=F when creating puck?? 

Thank you!

**Comment by dmcable** [comment]
Hi,

RCTD cannot be run on data that has been pre-processed by other methods. Our methods can account for noise in the data so no de-noising step is necessary beforehand.

Best,
Dylan
