### ISSUE TITLE
Correctly designing multi-replicate multi-batch experiment for meta-regression analysis

### ISSUE THREAD

**Issue by krademaker** [dmcable/spacexr#162]
Hi Dylan,

I am working on 10x Visium data from an experiment with a total of 4 case and 4 control brain samples, each being independent biological samples. Cases/controls have been jointly sequenced in several batches, such that I have this design:

| Sample | Batch | Control |
|--------|-------|---------|
| A      | 1     | 1       |
| B      | 1     | 0       |
| C      | 1     | 1       |
| D      | 1     | 0       |
| E      | 2     | 0       |
| F      | 2     | 1       |
| G      | 3     | 0       |
| H      | 3     | 1       |

And if necessary we have metadata on the sample age and gender. Furthermore, we have annotated the spatial barcodes to known anatomical regions, such that covariates for different regions are available in the `explanatory.variable` format described in the vignettes.

I am now following the population meta-regression vignette with the aim of testing for cell-type specific DE in various anatomical regions between cases and controls. Visium spots have already been mapped to a brain scRNA reference, and I am now preparing data for meta-regression.

The population meta-regression vignette mentions that `group_ids` is used to assign replicates to groups, in that case of cerebellum slices to the same group. However, how should I use `group_ids` in the case/control setting? Should it for instance be 0 for controls and 1 for cases, or does group refer to the experimental batch from which samples originate?

In any case, the `meta.design.matrix` for meta-regression can also be used to model case/control, batches, as well as age / gender, and the `meta.test_var` parameter can then be set to the case/control variable. So what exactly should be set in `group_ids` and how would it impact the analysis?

Thank you very much in advance,
Koen

**Comment by dmcable** [comment]
Hi Koen,

The `group_ids` variable is not used for meta-regression. Only for the default population inference of a single parameter across all samples when one would like to model group-level variance. I believe this should answer your question, but please let me know if there is anything else.

Best,
Dylan

**Comment by krademaker** [comment]
Hi Dylan,

Thanks a lot for clarifying this!

Best,
Koen
