### ISSUE TITLE
RCTD's requirements for R version

### ISSUE THREAD

**Issue by yx-xiong** [dmcable/spacexr#164]
Hi! I encountered an error while trying to run RCTD, and the error message seems to indicate that my R version is too low to read the 'Qmat/Q_mat_3.rds' file in the 'extdata' folder. However, I can manually read this file. Can you please explain why this is happening?
The error is:
> Error in readRDS(system.file("extdata", "Qmat/Q_mat_3.rds", package = "spacexr")) : 
   ReadItem: unknown type 192, perhaps written by later version of R

And my sessionInfo is:
R version 4.2.3 (2023-03-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] spacexr_2.2.1

Thanks a lot!

**Comment by dmcable** [comment]
Hi, I am unfortunately unable to reproduce this issue when running the line:
`readRDS(system.file("extdata", "Qmat/Q_mat_3.rds", package = "spacexr"))`

This is tested with most recent version of R version 4.3.2 as well as 4.2.1. I don't think the version of R is the issue. Your R version should be fine, but I'm not sure what is causing this issue. Are you still getting this issue?
