### ISSUE TITLE
Cell weights >1 while running in full mode

### ISSUE THREAD

**Issue by ivykos** [dmcable/spacexr#166]
Hi there,

When running RCTD in full mode on Visium data, the resulting weights for some cell types is well above 1.0. Since the weights are cell type proportions in a spot, how should I interpret a cell weight greater than 1?

**Comment by dmcable** [comment]
If they are close to 1, then this can occur since RCTD is not constraining the sum to 1, and it can determine the total weight sum to be greater than 1. You should interpret by creating normalized weights by dividing each row of weights by the rowsum.

Best,
Dylan
