### ISSUE TITLE
Differential gene expression across multiple samples

### ISSUE THREAD

**Issue by jwhipman** [dmcable/spacexr#167]
Hi, I'm working with Visium data from samples post and prior treatment. Version 2.2.0 allows us to test across covariates but is there a way to test between two regions belonging to different experiments? Right now, we create explanatory variables for each experiment but I just want to compare the same one region in different visium datasets (before treatment vs after treatment) accounting for varied cell type frequencies within spots. Thanks in advance for the advice

**Comment by dmcable** [comment]
Yes, there is! Please see the population meta regression of our multi-sample vignette https://raw.githack.com/dmcable/spacexr/master/vignettes/replicates.html . Briefly, you do a meta regression with the covariate as a feature of each sample (i.e. experiment).

Best,
Dylan
