### ISSUE TITLE
How to keep the SpatialRNA?

### ISSUE THREAD

**Issue by Smilenone** [dmcable/spacexr#168]
When running RCTD, I don't want to remove any pixels in the spatial data. When I set UMI_min = 0, UMI_min_sigma = 0 in create.RCTD(), there are still some of the pixels removed. How to keep the SpatialRNA?

**Comment by dmcable** [comment]
I'm not exactly sure, but I believe that pixels are removed if the barcode names are not shared between the counts, coords matrices, and the nUMI list. Check that the names appear in all 3.

Best,
Dylan
