### ISSUE TITLE
Single cell dataset size

### ISSUE THREAD

**Issue by Jaimomar99** [dmcable/spacexr#171]
Hey, thanks a lot for this wonderful package. 

I have a question about the size of the single-cell dataset. I guess that the bigger the dataset, the more data and the better would be the results. However, I'm unsure about the optimal number of cells I should aim for when generating a single-cell dataset. I'm trying to find the right balance between performance and cost-effectiveness. Of course there is not correct answer, but if you could provide some insights I will appreciate it

For instance, would a dataset with 4k cells be sufficient, or should I aim for a larger number? Are there any research papers or methods that explore this correlation?
Jaime

**Comment by dmcable** [comment]
Hi Jaime, 

This is an interesting question. For what purpose are you generating a single-cell dataset? If it is for the purpose of using as the single-cell reference for RCTD, then we generally recommend at least 100 cells per cell type, although, more accurate results would be obtained to increasing this number to around 500. Beyond 1000 cells per cell type there are diminishing returns. I can speak to different applications if you have something else in mind.

Best,
Dylan
