### ISSUE TITLE
Question about using raw rather than normalized counts as single cell reference?

### ISSUE THREAD

**Issue by estellad** [dmcable/spacexr#172]
Hi there,

"Counts should be untransformed count-level data." is specified in your tutorial. 
Is there any reason we do not perform any normalization to both the single cell and the spatial count matrices?

Sincerely,
Estella

**Comment by dmcable** [comment]
Dear Estella,

The reason that our package inputs raw counts is that normalization is handled as part of our Poisson-lognormal regression. We scale the expected counts by N_umi, or the total number of counts per cell. 

Best,
Dylan
