### ISSUE TITLE
Differential Expression with Multiple Experimental Replicates and Multiple Regions

### ISSUE THREAD

**Issue by rpisalive** [dmcable/spacexr#176]
Hello,

I am trying to apply C-SIDE to look at the differential expression across 6 different regions in Visium slice. I have 3 replicates and each replicate contains the 6 regions. I tried to follow the example https://raw.githack.com/dmcable/spacexr/master/vignettes/replicates.html
I would like to define the 6 regions as the explanatory variable. Since the explanatory variable should range from 0 to 1, I wonder if I could assign 6 different values for the 6 regions. For example, region1: 0, region2: 0.2, region3: 0.4, region4: 0.6, region5: 0.8, region6: 1

Thanks in advance and would be great to have your advice!

**Comment by krademaker** [comment]
You could also consider a design matrix with 1 binary variable per region, this way you can model it as a discrete effect instead of a continuous one.

**Comment by rpisalive** [comment]
> You could also consider a design matrix with 1 binary variable per region, this way you can model it as a discrete effect instead of a continuous one.

Thanks a lot for the advice! I think I had a misunderstanding regarding the explanatory variable. With your suggestion, I am now on the right track and running run.CSIDE.replicates!
