### ISSUE TITLE
Is it possible to get simulation matrix  like singcell dada?

### ISSUE THREAD

**Issue by lilwo** [dmcable/spacexr#180]
Hi ! Thanks a lot for the great work!
I want to get a decomposed expression data , I know that in the past I could get the rows for genes and the columns for spot and cell type with get_decomposed_data. Now where can CSIDE get such a matrix? I want to use this data as single-cell data for cell communication analysis.
Thank you very much!

**Comment by dmcable** [comment]
Hi, `get_decomposed_data` is not in the current version of our package, but you can feel free to access it in old versions. One option is to subset to the singlet pixels. For cell-cell communication analysis, we recommend using C-SIDE to detect cell-to-cell interactions.

**Comment by lilwo** [comment]
> Hi, `get_decomposed_data` is not in the current version of our package, but you can feel free to access it in old versions. One option is to subset to the singlet pixels. For cell-cell communication analysis, we recommend using C-SIDE to detect cell-to-cell interactions.

Thanks a lot
