### ISSUE TITLE
  medv hardcoded value in run.CSIDE.single

### ISSUE THREAD

**Issue by baptiste-grs** [dmcable/spacexr#183]
Hello, 

Thanks for the nice tool ! I have a question regarding the `medv` value hardcoded as 0.5 in the `run.CSIDE.single` function. Does the function expect to have a covariate that is uniformly spread from 0 to 1 ? If the covariate has for instance a negative binomial distribution (way more datapoints with a value below 0.5 than above), the `medv` value used as a threshold to select cell types will be too harsh as it would look at too few cells above 0.5 (instead of an arbitrary threshold like 0.2 for instance). I've managed to work around this with one patient by creating a cell type filter with my own value of medv and then using `run.CSIDE` but when trying on multiple replicates it automatically calls `run.CSIDE.single` with that 0,5 value for `medv`. 

What are you recommendations to work around this when doing a population analysis ? Apply some transformations so that my covariate is more uniform between 0 and 1 ? Is there any other way of using the available functions to make it work ? Lowering the cell_type_threshold to low values seem to help but does it impact the quality of the outputs ? More generally do you have any advice on trying to get insights on rare cell types ? 

Thanks a lot !

**Comment by dmcable** [comment]
Hi,

Good question! There was a mistake in the code where the 0.5 value was supposed to be applied to `explanatory.variable` after 0-1 normalization. I have fixed this and made `medv` changeable. You are correct that 0.5 is not always the best threshold to use, so now you should be able to change it.

You can lower `cell_type_threshold` to analyze rare cell types, but the error bars will be larger. It is a trade off. Let me know if you have any more questions.

Best,
Dylan

**Comment by baptiste-grs** [comment]
Hello Dylan, thanks for your answer and help ! 😊 

Sounds great, let me know if I can help you reviewing the corresponding PR
