### ISSUE TITLE
RCTD results--many NA values

### ISSUE THREAD

**Issue by liyiwang0725** [dmcable/spacexr#212]
Hi, everyone!

Why did I get many NA values results after reflecting into spatial datasets?
`RCTD <- create.RCTD(query, reference, max_cores = 28)
RCTD <- run.RCTD(RCTD, doublet_mode = "doublet")
data<- AddMetaData(data, metadata = RCTD@results$results_df)
`
Thanks for your help!

**Comment by IsmaelMaza** [comment]
Hi,
I'm not a member of the spacexr team, but I believe that the reason of your NA's is that those barcodes are being removed when you create the RCTD object with `create.RCTD()`.

To verify this, you can compare the length of barcodes in your Spatial counts matrix and the ones in your RCTD file and see if you have dropouts:

`ncol(Spatial_Object_Counts)) == ncol(RCTD_object@spatialRNA@counts)`

If you want to keep all the barcodes, you need to modify the `UMI_min`, `UMI_max` , and `counts_MIN` arguments in the `create.RCTD()` function. Aside from increasing the running time, I do not know how adding low UMI and counts samples will impact the results of the RCTD anlysis.

I hope this information helps you.

**Comment by liyiwang0725** [comment]
> Hi, I'm not a member of the spacexr team, but I believe that the reason of your NA's is that those barcodes are being removed when you create the RCTD object with `create.RCTD()`.
> 
> To verify this, you can compare the length of barcodes in your Spatial counts matrix and the ones in your RCTD file and see if you have dropouts:
> 
> `ncol(Spatial_Object_Counts)) == ncol(RCTD_object@spatialRNA@counts)`
> 
> If you want to keep all the barcodes, you need to modify the `UMI_min`, `UMI_max` , and `counts_MIN` arguments in the `create.RCTD()` function. Aside from increasing the running time, I do not know how adding low UMI and counts samples will impact the results of the RCTD anlysis.
> 
> I hope this information helps you.

Thank you so much! Your suggestion worked for me.
