### ISSUE TITLE
de_genes of cell types that used in RCTD

### ISSUE THREAD

**Issue by AmoriLi** [dmcable/spacexr#51]
Hi,
Thanks for developing such a robust tool for spatial data deconvolution!
I have a naive question about the result of multi-mode, if it includes the DEGs of cell types that used in following deconvolution process, in another word, the genes that are found in get_de_genes. 

Thank u in advance!

**Comment by dmcable** [comment]
Hello,

Thank you -- the genes used for RCTD can be found in `myRCTD@internal_vars$gene_list_reg`. A larger gene list used only in the platform effect normalization can be found in `myRCTD@internal_vars$gene_list_bulk`.

Best,
Dylan

**Comment by AmoriLi** [comment]
> Hello,
> 
> Thank you -- the genes used for RCTD can be found in `myRCTD@internal_vars$gene_list_reg`. A larger gene list used only in the platform effect normalization can be found in `myRCTD@internal_vars$gene_list_bulk`.
> 
> Best, Dylan

Thank you for your quick response! 
Yeah, I see. But I don't know which genes are used to define each cell type, I mean, specific cell type's deg, which will provide more info.

And I also have another question about CSIDE. Such a nice work! While it can only perform on RCTD 'doublet mode' and 'full mode' because I found function 'run.CSIDE' with 'doublet_mode' parameter that only can set to be (default) doublet mode weights or full mode weights. So how can we deal with multi_mode result from RCTD? Thanks!

**Comment by dmcable** [comment]
To see which cell types have the highest genes expression, you can look at the cell type gene expression matrix:
`expr_matrix <- myRCTD@cell_type_info$info[[1]]`.

Then you can look at that matrix for any list of genes: `expr_matrix[gene_list,]`. The units are normalized expression (i.e. counts per 1 or proportion out of 1). For any cell type of interest, you can select the genes with maximum expression in this cell type.
