### ISSUE TITLE
which celltype list is recommended for each pixel in multi-mode? sub_weights or subseting confident sub_weights?

### ISSUE THREAD

**Issue by AmoriLi** [dmcable/spacexr#56]
Hi！
Dear Developers!
I am not sure about which result will be better when doing RCTD multi-mode.
Whether it will be better to subset the confident sub_weights in RCTD@results[[]] for each pixel rather than all sub_weights?
And I have checked the difference of cell type's total proportion using this two strategies. I found that some main cell types' total proportion shows difference while rare cell tyeps less(perhaps because their basic number are small)
Hope you can give some suggestions!
Thanks a lot!
![202203](https://user-images.githubusercontent.com/80192100/158382032-14e2be9a-dacb-47b0-ab73-7c7507913142.jpg)

**Comment by dmcable** [comment]
Hi Amori,

I think both approaches are valid, and I would recommend making the decision based on what seems to work better for your data. In multi-mode, if a cell type appears on a pixel without being confident, then it means that this cell type may be present on the pixel, but there is not enough information to determine with certainty.

The advantage of using all cell types from the entire `cell_type_list` is that more cell types will be detected and it will be less likely to miss a cell type that is present. The advantage of subsetting to the confident cell types is that it would reduce the chance of incorrect cell type predictions. Personally, I would first look at using all cell types in `cell_type_list`, and I would check if there appear to be systematic errors. If so, I would recommend reducing the used cell types to only the confident ones; it's a judgement call.

Another option is to lower `CONFIDENCE_THRESHOLD` (Default 10), which is the minimum change in likelihood (compared to other cell types) necessary to determine a cell type identity with confidence. Lowering this parameter to e.g. 5 would result in more cell types called as confident. This parameter can be set in the `create.RCTD` function, or, directly as:

`myRCTD@config$CONFIDENCE_THRESHOLD <- 5`

Hope this helps in deciding between the two strategies!
