### ISSUE TITLE
Error with 'run.CSIDE()', myRCTD@results have different structure than the tutorial data, RCTD@results slot can not be modified

### ISSUE THREAD

**Issue by DanielZucha** [dmcable/spacexr#57]
Hello spacexr team, 
in the beginning please let me thank you for all the amazing work you did with this package! Indeed, the tutorials, vignette, and the functionality is superb. I'm contacting you with an error when trying to run `run.CSIDE` function. Here is the console output with traceback:

![image](https://user-images.githubusercontent.com/33066869/159281344-c2370b7c-e920-4d62-af90-c8795f40714a.png)

To solve this, I have tried to run the RCTD in different modes ("multi" vs "full"), or using your native function for replicates ('create.RCTD.replicates', 'run.RCTD.replicates'), just to be sure that not just one type of input is required for the follow up CSIDE analysis (generally, I am following your steps as described in here: https://raw.githack.com/dmcable/spacexr/master/vignettes/visium_full_regions.html). RCTD works great for me under all instances and the RCTD results are robust. CSIDE however prints out this very same error for any of them. 

The traceback message focused my attention on the myRCTD@results. When comparing the different modes, I am getting the same structure of the myRCTD@results every time when compared between each-other. Here is how it looks like in Rstudio:
![image](https://user-images.githubusercontent.com/33066869/159284072-ea319cb3-4c54-46a8-a960-e1afeae52c00.png)
Number of elements in the myRCTD@results equals to the number of spots in this Visium section. 

However, when I reproduced the RCTD and CSIDE of your tutorial data ('myRCTD_visium_full.rds') as in (https://raw.githack.com/dmcable/spacexr/master/vignettes/visium_full_regions.html)), and compared the myRCTD@results folders, the difference is clearly noticeable, as your results folder is stored in more convenient format:
![image](https://user-images.githubusercontent.com/33066869/159284728-4259c4aa-dcf0-45d1-bb34-62b9ed4c8fdb.png)

This difference is in-line with the error as I am getting and now I know what can't be accessed in my RCTD file. I tried to modify the results folder, but to no avail, as I am getting error message 'Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “dgCMatrix” is not valid for @‘results’ in an object of class “RCTD”; is(value, "list") is not TRUE'. 

Now I am not sure how to advance further, what to change/modify. I have started using your package just a week ago, so maybe am I running some newer version for parts of the package? I am sorry for bothering you with this inconvenience, but I could't find this topic in any of the open or closed issues. Keep up the excellent work and thank you in advance.

**Comment by dmcable** [comment]
Dear Daniel,

Thank you for your comments and your detailed information. I am happy to look into this issue.  I believe the fastest way would be if you please send me the objects (.rds or .Rdata files) used run the `run.CSIDE` command to my email at dcable@mit.edu . I will then be able to debug the issue and get back to you. Thank you.

Dylan

**Comment by cxlpanpan** [comment]
Hi,@dmcable, great respect for your amazing work  in this field, and @DanielZucha ,thanks for your detailed information. I met the same error with you when running  run.CSIDE.single,  and also has same structure of myRCTD@results with you.  Have you solved this problem yet ?  And would you mind sharing the solution with us ?  and dear @dmcable , may I send you the objects to ask for your help ?
![1](https://user-images.githubusercontent.com/115337722/194694503-44479933-b203-44bb-b100-e2de266d9e4e.PNG)
![2](https://user-images.githubusercontent.com/115337722/194694508-39646cdf-aea1-4145-ba6a-0a6277fc7598.PNG)

**Comment by dmcable** [comment]
Yes, please send me your objects, and I will fix your issue.

**Comment by cxlpanpan** [comment]
> Yes, please send me your objects, and I will fix your issue.

Thanks! I've sent to your email(title is "ask for your help with error in run.CSIDE.single"), thanks for your timely help!

**Comment by dmcable** [comment]
Hi, I have implemented support for this case. You should be able to run your code now.

**Comment by cxlpanpan** [comment]
> 

I really apologize for my mistake with attached files and delayed reply. Thanks a lot for your great support and such prompt reply. It works well now! Thanks!
