### ISSUE TITLE
Compatibility issue with older version using package name = RCTD

### ISSUE THREAD

**Issue by simoncmo** [dmcable/spacexr#58]
Hi, we have been using older RCTD before the package is renamed to `spacexr`

Now all the older objects throw error messages upon attempting to access its content 
```
Loading required package: RCTD

Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘RCTD’”
ERROR while rich displaying an object: Error in .requirePackage(package): unable to find required package ‘RCTD’ 
```

Currently, all my attempts to manually modify the object failed. e.g. Manually changing the class name failed halfway
I poke around a little bit and haven't found a great way to convert old objects to recognize new `spacexr` package names while package `RCTD` no longer exists.

Since `C-SITE` seem to depend on the RCTD output and rerunning everything using the new package is time-consuming and seemed unnecessary. 
Could you advise a way to convert the older RCTD object to be compatible with the new package?
Perhaps a code snippet would be great, but I can probably figure something out too if there's a general direction.

Thanks!
Simon

**Comment by dmcable** [comment]
Dear Simon,

Once you have the logic loaded into memory, please see the `convert.old.RCTD` function to solve this issue. Sometimes, R will give an error for trying to load in an object if the `RCTD` package no longer exists. The best solution I have found to this issue is to create and load a nearly empty `RCTD` dummy package, found here: https://github.com/dmcable/spacexr/blob/master/resources/RCTD_0.1.0.tar.gz 

Hope this helps.

Dylan

**Comment by JZL** [comment]
Not an RCTD-dev, just a heavy user.

This is a hack and I think it's still worth figuring how to get spacexr to work. But I have had trouble in the past when reloading objects from `RDS`/`qs`, where the S3 class is so heavily tied to package name, that it just immediately rage-quits. 

You could try to use `devtools::load_all` on a version of the repo `checkout`'d from before the spacexr change (@dmcable  it might be nice to have set a formal github release for the most finalized version of RCTD, before the spacexr change so people can find that commit easier, also for referencing solely RCTD in other papers)

Alternatively, the RCTD/spacexr namespace is just defined at the first line of the `DESCRIPTION` file. So I haven't been above downloading a package, changing that one line, and then `devtools::load_all` for temporary use / `devtools::install` for permanent use.

**Comment by dmcable** [comment]
Thanks. I just added the man file for `convert.old.RCTD`.

Regarding `spacexr:::convert_old_RCTD`, I agree that it should not exist, and I can't find this function in the current version of the Github repo. If you have a link to the file containing this function, that would be useful.

Here is the output on my device for installing the RCTD dummy package. 
![Screen Shot 2022-04-06 at 10 14 32 AM](https://user-images.githubusercontent.com/40443769/161995349-670f6ce1-419e-4908-b767-87278386c8f4.png)
I have also seen the same result on the machine of a colleague. I am not sure exactly why it is causing an error on your computer. Another option is that it takes a few minutes in Rstudio to create a new package (named RCTD); I would recommend trying that.

**Comment by AmoriLi** [comment]
> Hi, we have been using older RCTD before the package is renamed to `spacexr`
> 
> Now all the older objects throw error messages upon attempting to access its content
> 
> ```
> Loading required package: RCTD
> 
> Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
> “there is no package called ‘RCTD’”
> ERROR while rich displaying an object: Error in .requirePackage(package): unable to find required package ‘RCTD’ 
> ```
> 
> Currently, all my attempts to manually modify the object failed. e.g. Manually changing the class name failed halfway I poke around a little bit and haven't found a great way to convert old objects to recognize new `spacexr` package names while package `RCTD` no longer exists.
> 
> Since `C-SITE` seem to depend on the RCTD output and rerunning everything using the new package is time-consuming and seemed unnecessary. Could you advise a way to convert the older RCTD object to be compatible with the new package? Perhaps a code snippet would be great, but I can probably figure something out too if there's a general direction.
> 
> Thanks! Simon

Hi, have u solved this problem? I'm also facing it now

**Comment by dmcable** [comment]
Hi @AmoriLi , yes, please try the steps in the above thread, in particular: https://github.com/dmcable/spacexr/issues/58#issuecomment-1076834316 . 

Please post how this works out for you.

**Comment by AmoriLi** [comment]
> 

Thanks for quick reply! I also can not install the file you provided. It posted error as follows
![9fbe6be0a4adbdc71221d28cba248ed](https://user-images.githubusercontent.com/80192100/164713272-cdbd47e2-2e73-4e3e-9b95-81590ec41fd2.png)

And the file path should have no mistake when checked (running in docker container)
![9dc62dfaf573c0af15293377ae67c6d](https://user-images.githubusercontent.com/80192100/164714039-33f44e06-0b47-4e50-8684-e366a1343ea6.jpg)

**Comment by dmcable** [comment]
Dear @AmoriLi and @simoncmo ,

I believe that the issue comes down to obtaining the correct file. In particular, the following command should be used to download the correct `RCTD_0.1.0.tar.gz` file:
`wget https://github.com/dmcable/spacexr/raw/master/resources/RCTD_0.1.0.tar.gz`

One situation in which I have detected this error is if the incorrect file is downloaded as follows:
`wget https://github.com/dmcable/spacexr/blob/master/resources/RCTD_0.1.0.tar.gz`

Note this the above link does not refer to the `RCTD_0.1.0.tar.gz` file, but rather the HTML page of the GitHub website. Rather, one must use the first **raw** link to the file posted above. Alternatively, you can clone the package and navigate to the resources directory, or you can click the download button on the GitHub webpage.

**Comment by AmoriLi** [comment]
> Thank you so much! It solved the error. But it had no reponse through wget (maybe the poor network). Finally succeed via directly downloading the file on github. Thanks for your patience and kind assistance!
