### ISSUE TITLE
devtools installation error

### ISSUE THREAD

**Issue by yiranzhimo** [dmcable/spacexr#59]
Hello, Thank you for your work！

According to the README‘s Installation step:

> install.packages("devtools")
> devtools::install_github("dmcable/spacexr", build_vignettes = FALSE)

But it doesn't work.

Is there other ways to install spacer？

**Comment by dmcable** [comment]
Hello,

I will need more information to help you with your issue. Can you please post a screenshot of the error in R after executing these commands?

-DC

**Comment by yiranzhimo** [comment]
> Hello,
> 
> I will need more information to help you with your issue. Can you please post a screenshot of the error in R after executing these commands?
> 
> -DC

Hello, thank you for your reply.

I figured out why I received an error when installing because of the network.

I tried other ways to download spacexr package, and I succeeded.

Thank you for your help.

**Comment by Biocxifu** [comment]
这包太大了，400多M，自己Windows电脑要么挂VPN，linux服务器真的不好弄，手动下的包竟然是windows版本的，装都装不上，我崩溃了，中国连github的网速就是太烂了，这400M是真的下载不下来。请问你是什么系统呀，咋解决的。

**Comment by yiranzhimo** [comment]
> 这包太大了，400多M，自己Windows电脑要么挂VPN，linux服务器真的不好弄，手动下的包竟然是windows版本的，装都装不上，我崩溃了，中国连github的网速就是太烂了，这400M是真的下载不下来。请问你是什么系统呀，咋解决的。
我记得我当时是 CentoS 的系统，我是网络问题，换了能链接上外网的服务器节点就解决了。
