### ISSUE TITLE
plot_all_cell_types 

### ISSUE THREAD

**Issue by yiranzhimo** [dmcable/spacexr#60]
hello, Thank you for your work to create such a useful tool.

I have a question about the function "plot_all_cell_types".

Dose the function "plot_all_cell_types" use the colnumn of "first type" or "second type"?

![Screen Shot 2022-04-11 at 9 34 26 AM](https://user-images.githubusercontent.com/40296363/162650805-d3e7c3c2-e3fe-4378-aa85-8ec1d369366a.png)

**Comment by dmcable** [comment]
The function `plot_all_cell_types` only plots the primary cell type per pixel. However, there are other functions such as `plot_weights_doublet` (doublet mode) or `plot_weights_unthreshold` (full mode) that plot every cell type on each pixel.

**Comment by yiranzhimo** [comment]
> The function `plot_all_cell_types` only plots the primary cell type per pixel. However, there are other functions such as `plot_weights_doublet` (doublet mode) or `plot_weights_unthreshold` (full mode) that plot every cell type on each pixel.

so, what is the primary cell type? is it the "first type"?

**Comment by dmcable** [comment]
Yes, that is correct. The meaning of `results$weights_doublet$first_type` is the proportion of the first cell type on the pixel. The identity of the cell type can be found in `results$results_df$first_type`.

**Comment by yiranzhimo** [comment]
> Yes, that is correct. The meaning of `results$weights_doublet$first_type` is the proportion of the first cell type on the pixel. The identity of the cell type can be found in `results$results_df$first_type`.

For one cell,  the proportion of the first cell type is lower than the second type on the pixel.

**Comment by dmcable** [comment]
That can occur, and it's not a problem. In that case, keep in mind that there are two cell types on that pixel that are close in proportion.
