### ISSUE TITLE
Hippocampus data

### ISSUE THREAD

**Issue by Vivianstats** [dmcable/spacexr#61]
Dear Dylan,

Thank you for your quick responses to my previously questions.
I wonder where I can download the cropped data of Slide-seq hippocampus data shown in your Figure 5?
For the scRNA-seq reference, is the SCRef_hippocampus.RDS.zip file on Single Cell Portal (https://singlecell.broadinstitute.org/single_cell/study/SCP948/robust-decomposition-of-cell-type-mixtures-in-spatial-transcriptomics#study-visualize) the correct one to use?

Thank you!
Vivian

**Comment by dmcable** [comment]
Hello Vivian,

Yes, that is correct for the reference. For the cropped Slide-seq data, please use puckCropped_hippocampus.rds, also available at the SCP portal.

Best,
Dylan

**Comment by Vivianstats** [comment]
Thank you, Dylan! But I didn't find cell types in the Seurat object of the scRNA-seq data. Is this information also available at SCP?

**Comment by dmcable** [comment]
Yes -- it is in the Seurat object at `reference@meta.data$liger_ident_coarse`.

**Comment by Vivianstats** [comment]
Found it. Thanks a lot!
