### ISSUE TITLE
spacexr cannot be installed through devtools::install_github

### ISSUE THREAD

**Issue by yu-tong-wang** [dmcable/spacexr#62]
Hello @dmcable , I am using R version 4.1.3 on MacOS (x86_64-apple-darwin17.0 (64-bit)), and below is the error message I got when trying to install the package. 

```
> # install.packages("devtools")
> devtools::install_github("dmcable/spacexr")
Downloading GitHub repo dmcable/spacexr@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/dmcable/spacexr/tarball/HEAD' failed
```

I am currently using a work-around by first git clone and then 

> devtools::install("~/Documents/GitHub/spacexr")

which allows me to manually import the spacexr library.

**Comment by yu-tong-wang** [comment]
I also have a quick question about data accessibility when trying to reproduce the simulation result (Fig 2) in C-SIDE, if you do not mind. What is `"../../../spacexr/data/Reference/10xCer/reference.rds"` in 
https://github.com/dmcable/spacexr/blob/master/AnalysisCSIDE/Figures/figure2.Rmd#L27 ?

I could not find relevant scripts to generate 10xCer-related data from the Visium data provided in ./extdata, maybe ./10xCer is not an intermediate result directory but from some external single cell reference?

Thank you! (Let me know if it is better to create a new issue with a different issue title for this :) )

**Comment by dmcable** [comment]
Dear Yutong,

Interesting, I haven't been able to reproduce this issue on my computer, and I am not exactly sure what is causing it. The workaround you pursued is good. Here are some potentially relevant webpages I found:

https://stackoverflow.com/questions/65273115/r-devtoolsinstall-githubjzsbioinfo-aprd-error-in-utilsdownload-fileurl
https://github.com/r-lib/devtools/issues/2303
https://github.com/forestgeo/learn/issues/102

Hope this helps.

Best,
Dylan

**Comment by dmcable** [comment]
The cerebellum 10x reference can be found at the scp portal: https://singlecell.broadinstitute.org/single_cell/study/SCP948/robust-decomposition-of-cell-type-mixtures-in-spatial-transcriptomics

Please note that ./extdata contains toy or downsampled datasets and not the full original data.

Best,
Dylan

**Comment by yu-tong-wang** [comment]
Thank you for your helpful response, Dylan.

**Comment by Jtrachsel** [comment]
I think this issue is related to the download from github timing out.  Our network is slow and we were having this same issue.  When I increased the 'timeout' option the install worked fine.  

`options(timeout = 600000000)
devtools::install_github("dmcable/spacexr")
`

**Comment by jebard** [comment]
> I think this issue is related to the download from github timing out. Our network is slow and we were having this same issue. When I increased the 'timeout' option the install worked fine.
> 
> `options(timeout = 600000000)`
> 
> `devtools::install_github("dmcable/spacexr")`

I know this thread is a bit old but I just hit this same error today, and setting the timeout parameter cleared the errors and installed successfully.

**Comment by cmiciano** [comment]
also was receiving the above error, thank you @Jtrachsel
