### ISSUE TITLE
error: there is no package called ‘RCTD’

### ISSUE THREAD

**Issue by liukc19** [dmcable/spacexr#68]
I'm running code in the spacexr/analysispaper/mainfigures/figure1.rmd and the following error occurs

> puck <- myRCTD@spatialRNA
Loading required package: RCTD
Error in .requirePackage(package) : 
  unable to find required package ‘RCTD’
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘RCTD’
Loading required package: RCTD

it seems that not all your including of this package has been renamed to spacexr
so how can i solve this problem,thank you.

**Comment by dmcable** [comment]
Hello, for objects that were previously created with the RCTD package, please see the following thread for installing a dummy RCTD package to avoid the error: https://github.com/dmcable/spacexr/issues/58
