### ISSUE TITLE
missing data files and R script

### ISSUE THREAD

**Issue by liukc19** [dmcable/spacexr#69]
Hello, I'm running code in figure 3.Rmd, but couldn't find these files:
```
#Command used to save the data from the gather_results.R script:
#save(puck_d, iv, results, file = 'Data/SpatialRNA/Puck_Viz/results/gathered_results.RData')
#loading in that data:
refdir = '../../Data/Reference/DropVizHC'
load('../../Data/SpatialRNA/Puck_Viz/results/gathered_results.RData')
results_df <- results$results_df
metadir <- file.path(paste0('../../','Data/SpatialRNA/Puck_Viz'),"MetaData")
meta_data <- readRDS(file.path(metadir,"meta_data.RDS"))
```
The "gathered_results.RData" and the "meta_data.RDS" seem not to be in the given dataset, and the "gather_results.R" not in this repository

**Comment by dmcable** [comment]
Please see the following link for these files including `gathered_results.rds` and `meta_data.rds`: https://www.dropbox.com/s/3igvi3j85hbqz6z/Figure3.zip?dl=0

**Comment by liukc19** [comment]
Thank you for your help, these data files help me a lot.
I noticed that in the code of Figure4~Figure6 you all used data generated from the "gather_results.R" script. Could you tell me how to find this script? 
Any help would be appreciated.

**Comment by dmcable** [comment]
Hi, the `gather_results.R` script is outdated given the current version of RCTD. For current functionality for running RCTD (including the functionality of `gather_results`), please see our vignettes https://github.com/dmcable/spacexr/tree/master/vignettes.

**Comment by liukc19** [comment]
Thanks a lot for your help.
I searched the `gather_results()` function but only found the definition `gather_results <- function(RCTD, results)`. There is no other explanations about it in the `spacexr_manual_2.0.0` or other place, so I'm curious what this input `results` means.

**Comment by dmcable** [comment]
The function `gather_results` is an internal function called by `run.RCTD` (of which documentation is available), and it organizes the output of RCTD on each pixel. The RCTD `results` object is explained here: https://github.com/dmcable/spacexr/tree/master/documentation.
