### ISSUE TITLE
run.CSIDE.replicates.error

### ISSUE THREAD

**Issue by AmoriLi** [dmcable/spacexr#70]
Hi, dear developers!
when running CSIDE.replicates as follows:
![Screen Shot 2022-04-26 at 9 31 30 AM](https://user-images.githubusercontent.com/80192100/165201125-33629b35-a596-4088-a893-c099343373a2.png)

I got the error like this:
"Error in if (any(p_val[order(p_val)] < thresh)) {: missing value where TRUE/FALSE needed"
![Screen Shot 2022-04-26 at 9 33 01 AM](https://user-images.githubusercontent.com/80192100/165201244-a77b9387-8138-4825-97af-c97eee92bdfb.png)
 

Do you know the reason? Thanks very much

**Comment by dmcable** [comment]
Hi, happy to look into it. Can you please send me your input objects (dcable@mit.edu), so I can debug the issue? Thanks.
