### ISSUE TITLE
Nanostring CTA data feasibility

### ISSUE THREAD

**Issue by yeswzc** [dmcable/spacexr#72]
Hi,
Is this method feasible for data generated using Nanostring GeoMx Cancer Transcriptome Atlas (CTA)?

Thank you!

**Comment by dmcable** [comment]
Hello, 

Yes, we have collaborators who have previously applied RCTD and C-SIDE to GeoMx data.

Best,
Dylan

**Comment by yeswzc** [comment]
Thank you! 
Do you know if there is a big/small decrease of deconvolution power that the CTA has only ~1800 genes?

**Comment by dmcable** [comment]
It depends on the dataset, but 1800 genes is usually sufficient to assign cell types.

**Comment by yeswzc** [comment]
> 

Thank you!
