### ISSUE TITLE
My plot was a rectangle rather than a square

### ISSUE THREAD

**Issue by yunbokai** [dmcable/spacexr#73]
Hi spacexr team,

Thanks  for the great package and functionalities! 
I got a 10x Visium data.
After sucessfully runing
```
myRCTD <- create.RCTD(puck, reference, max_cores = 4)
myRCTD` <- run.RCTD(myRCTD, doublet_mode = "full")
```
I found that some spots were filtered out . And after running
`plot_weights_unthreshold(cell_type_names, spatialRNA, resultsdir, norm_weights) `
I found that my plot was a rectangle rather than a square, which was different from my origin image. I wonder how to deal with this problem.
![图片](https://user-images.githubusercontent.com/94819980/166434640-bfe0151f-ca98-4001-a57c-1ae3674d0dfa.png)

Any help will be really appreciated.

Thanks again for the package,
18k

**Comment by dmcable** [comment]
You can preserve the coordinates by adding `+ ggplot2::coord_fixed()` 

More information about how to modify `ggplot2` plots can be found here: https://ggplot2.tidyverse.org/

Another option is to create plots from scratch. In this case, all the data needed for plotting is stored within the RCTD object.

**Comment by yunbokai** [comment]
Thanks a lot for your answers!
