### ISSUE TITLE
loadSparseDge cannot load the Barcode and Gene names?

### ISSUE THREAD

**Issue by Smilenone** [dmcable/spacexr#74]
Hi, I am trying to use dropSeqProcess (https://github.com/dmcable/spacexr/blob/dev/AnalysisPaper/Rscripts/dropSeqProcess.R) to onvert the hippocampus single-cell dataset to a Seurat object.

However, it seems that the function loadSparseDge cannot load the Barcode and Gene names so that the value of  common_barcodes is nan.   I wonder how to deal with this problem.

Any help will be really appreciated!

**Comment by Smilenone** [comment]
Could you provide raw dge files of the references you used in the paper at your convenience?


Thanks in advance!


Qunlun




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dmcable/spacexr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 凌晨1:53
***@***.***&gt;;
抄送:&nbsp;"Qunlun ***@***.******@***.***&gt;;
主题:&nbsp;Re: [dmcable/spacexr] loadSparseDge cannot load the Barcode and Gene names? (Issue #74)





 
Hi,
 
This script is outdated since RCTD no longer uses Seurat objects directly. Instead, please see the following tutorial for creating the RCTD Reference object: https://raw.githack.com/dmcable/spacexr/master/vignettes/spatial-transcriptomics.html
 
Dylan

**Comment by dmcable** [comment]
You can find the e.g. hippocampus reference here: https://singlecell.broadinstitute.org/single_cell/study/SCP948/robust-decomposition-of-cell-type-mixtures-in-spatial-transcriptomics

SCRef_hippocampus.RDS

The reference is in Seurat format, and you can access the raw counts (DGE) within the object. Please let me know if you have any other questions.

**Comment by Smilenone** [comment]
where can I find the&nbsp;cerebellum reference? It seems that&nbsp;https://singlecell.broadinstitute.org/single_cell/study/SCP948/robust-decomposition-of-cell-type-mixtures-in-spatial-transcriptomics&nbsp;this website only provide subsampled cerebellum reference data.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dmcable/spacexr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月2日(星期四) 凌晨1:17
***@***.***&gt;;
抄送:&nbsp;"Qunlun ***@***.******@***.***&gt;;
主题:&nbsp;Re: [dmcable/spacexr] loadSparseDge cannot load the Barcode and Gene names? (Issue #74)





 
You can find the e.g. hippocampus reference here: https://singlecell.broadinstitute.org/single_cell/study/SCP948/robust-decomposition-of-cell-type-mixtures-in-spatial-transcriptomics
 
SCRef_hippocampus.RDS
 
The reference is in Seurat format, and you can access the raw counts (DGE) within the object. Please let me know if you have any other questions.

**Comment by dmcable** [comment]
The subsampled cerebellum reference is used in the study, and the original reference is present here: https://www.nature.com/articles/s41586-021-03220-z
