### ISSUE TITLE
Identify marker genes used

### ISSUE THREAD

**Issue by stephenwilliams22** [dmcable/spacexr#75]
After running `run.RCTD` is there an easy way to identify which genes were used as marker genes (or marker gene profile) for each cell type? Even a list of differently expressed genes would be useful. I've dug into the code a bit but there doesn't seem to be anything obvious.

**Comment by dmcable** [comment]
Hi Stephen,

For RCTD, the list of marker genes used are in `myRCTD@internal_vars$gene_list_bulk` and `myRCTD@internal_vars$gene_list_reg` for the platform effect and pixel-wise steps, respectively. For more information, see #39 .

Dylan
