### ISSUE TITLE
issues with run.CSIDE.regions

### ISSUE THREAD

**Issue by wanliw96** [dmcable/spacexr#76]
Hi,

When I was running run.CSIDE.regions, the test_mode is set to 'categorical', and I keep getting an error of                                  
'Error in get_sig_genes(puck, myRCTD, gene_list_tot, cell_types, my_beta, : object 'both_genes' not found'.                                          After checking the source code, I found in function 'gene_sig_genes', the object 'both_genes' is only defined for test_mod=='individual' but not for 'categorical'. Could you please help to check and change it in the package? Thanks.

**Comment by dmcable** [comment]
Thank you for this issue. This typo has been fixed.

Dylan
