### ISSUE TITLE
Is it possible that Reference use TPM instead of counts for reference

### ISSUE THREAD

**Issue by yunbokai** [dmcable/spacexr#80]
Hi,

My reference comes from Smart-seq2 and the results are composed of "TPM" rather than"count". I wonder to know that whether it is worked for RCTD?

Thank you.

**Comment by dmcable** [comment]
Hi, apologies for the late reply. You can either multiple by 1 million to achieve raw counts, or the RCTD `Reference` function will also work correctly if you set `require_int = TRUE`.

Best,
Dylan
