### ISSUE TITLE
cell-type specific Differential expression

### ISSUE THREAD

**Issue by vravik** [dmcable/spacexr#83]
Hey guys,

I was wondering if it'd be possible to perform a multivariate regression of gene expression in cell type A against proximity to other cell types (B-D say), so we can say what genes are differential in the cell type of interest as a function of neighboring each of the others? Something like the interaction-changed genes functionality in giotto, without having to use a one-hot encoding of each spot?

**Comment by dmcable** [comment]
Hello,

Yes, it is possible to perform multivariate regression with C-SIDE given multiple covariates such as proximity to other cell types. Please see `run.CSIDE` and `run.CSIDE.general`.

Dylan
