### ISSUE TITLE
Error when running the run.CSIDE.single function based on Visium dataset

### ISSUE THREAD

**Issue by LanqiGong** [dmcable/spacexr#85]
Hi,

I found spacexr is a very useful tool to deconvolute spatial transcriptome data and study cell-cell interactions. Recently, I have used the run.CSIDE.single function to study cell-cell interactions based on our Visium dataset. However, I have encountered an error showing Error in dimnames(all_vals) <- `*vtmp*` : length of 'dimnames' [1] not equal to array extent
![image](https://user-images.githubusercontent.com/77276012/178698026-83fedefa-46cc-4292-ad49-1f5cb7928252.png)

The code is shown below:

################
B_weight <- myRCTD@results$weights[,'tumor']
B_med <- median(B_weight)
B_weight[B_weight>=B_med] <- 1
B_weight[B_weight<B_med] <- 0

plot_puck_continuous(myRCTD@spatialRNA, rownames(myRCTD@spatialRNA@coords), B_weight, size = 1) 

myRCTD@config$max_cores <- 1
cell_types <- c('Immune','22')
myRCTD <- run.CSIDE.single(myRCTD, B_weight, cell_types = cell_types, gene_threshold = 5e-5, cell_type_threshold = 10, 
                           fdr = 0.01, doublet_mode = F, weight_threshold = NULL)
################

I attached the myRCTD which worked perfectly fine with other functions in spacexr. So I was wondering if you could suggest me how to get the run.CSIDE.single function done for our dataset. Thank you very much for your help.
[myRCTD_patient_1_NPC_rds_full.zip](https://github.com/dmcable/spacexr/files/9100451/myRCTD_patient_1_NPC_rds_full.zip)

**Comment by dmcable** [comment]
Dear Lanqi,

Thanks for bringing up this issue. Should be fixed now. It turns out, we had erroneously left in a line from debugging that always set the iteration to 346. Please let me know if there are any other issues.

Best,
Dylan

**Comment by LanqiGong** [comment]
> Dear Lanqi,
> 
> Thanks for bringing up this issue. Should be fixed now. It turns out, we had erroneously left in a line from debugging that always set the iteration to 346. Please let me know if there are any other issues.
> 
> Best, Dylan

Hi Dylan,

Thank you very much for your help.
