### ISSUE TITLE
read.VisiumSpatialRNA() function works for outputs from Space Ranger v1.3.1 but not v2.0.0

### ISSUE THREAD

**Issue by AndrewGottscho** [dmcable/spacexr#86]
This command works for a dataset run with Space Ranger 1.3.1:

`VisiumData<-read.VisiumSpatialRNA("/path/to/Visium_FFPE_Mouse_Brain_RUN2/outs")`

However when I run with the identical dataset run with Space Ranger 2.0.0 (released today 7/18/22) I get this error

`Error: '/path/to/Visium_FFPE_Mouse_Brain_RUN2/outs/spatial/tissue_positions_list.csv' does not exist.`

(Not the actual path, I simplified the path in this issue)

I double checked the output directories produced from Space Ranger 1.3.1 and 2.0.0. The 2.0 version has the file renamed to "tissue_positions.csv" instead of "tissue_positions_list.csv"

I tried renaming the 2.0 "tissue_positions.csv" to "tissue_positions_list.csv", but there is more to it than that -- the format now seems different.

Thanks! Andrew

**Comment by dmcable** [comment]
Good point, it is fixed now, thank you.
