### ISSUE TITLE
how to get Cell type - specific gene expression values in full mode ？

### ISSUE THREAD

**Issue by khl0798** [dmcable/spacexr#87]
For example, with 10x Visium data, such as the full Mode model, we want to know the cell type-specific gene expression values resolved in each spot. How do I get this?

For Cell type-specific Inference of Differential Expression (C-side), full mode mode, We also want to know cell type specific gene expression values in each spot based on explanatory variables？

**Comment by dmcable** [comment]
Hello, to get cell type specific gene expression without differential expression, you can run C-SIDE with only an intercept term. To get differential expression, you should include at least one explanatory variable. 

After running DE, you can access the cell type specific gene expression values by looking at the `gene_fits$mean_val` (only the DE parameter in case of single explanatory variable), `gene_fits$all_vals` (all parameters) values, and the standard errors in `gene_fits$s_mat`. To see the results for only the significant genes, look here: `myRCTD@de_results$sig_gene_list`. More info here https://github.com/dmcable/spacexr/tree/master/documentation.

**Comment by khl0798** [comment]
Thank you very much for your reply.But there are still three questions that puzzle me.

1. ”to get cell type specific gene expression without differential expression, you can run C-SIDE with **only an intercept term**.“，I still don't know how to understand this. 
`run.CSIDE.single(myRCTD, explanatory.variable=NULL)` ?

3. without differential analysis, doublet mode, single cell types were used to map 10x visium spot, and epithelial cell types were found to be dominant. Then, Subgroup of epithelial cells were used to map 10x visium spot. then the weights of subgroup of epithelial cells should multiply total weights of the epithelial cell type ?

4. Or for example，without differential analysis,doublet mode, we found epithelial cells and endothelial cells accounted for the majority, and epithelial cells accounted for a higher proportion. Then, Subgroup of epithelial cells were used to map 10x visium spot. finally,The results of epithelial subdivision showed that subgroups 1,2 were predominant. Finally, epithelial subgroups 1,2 and endothelium are selected to be re-mapped as a whole.

My question is ,Which is more appropriate, for point 2 and point 3? or how to use the subgroup of specific celltypes which accounted for a higher proportion?

**Comment by dmcable** [comment]
1. You can run, for example, the following code to run C-SIDE with only an intercept:
```
barcodes <- intersect(names(myRCTD@spatialRNA@nUMI), colnames(myRCTD@spatialRNA@counts))
X <- as.matrix(rep(1, length(barcodes)))
rownames(X) <- barcodes
RCTD <- run.CSIDE(RCTD, X, barcodes)
```
2-3. I think both are good ideas, but method 3 would be preferred because it includes the other cell type (endothelium) in the final mapping. I would use full mode for the final remapping. 

Best,
Dylan

**Comment by khl0798** [comment]
hi, Dylan,  Thank you very much for your prompt reply.

1.  for point 2，that is， why not the weights of subgroup of epithelial cells should **multiply** **total fraction** of the epithelial?  In fact, Epithelial cells account for only a fraction of the results of mapping across multiple cell types(for example, B cell, Tcell, epithelial et.al )?.

3.  Assuming 10x Visium has 5-10 cells per spot, similar to bulkRNA, why not choose doublet mode? As we know, there is a high probability that may be two cell types dominate the distribution of 10 cells.  or it may be not possible  that 5-10 cells include at least 3 major cell types ?

best
candy

**Comment by dmcable** [comment]
Dear Candy,

1.  You can do a statistical test for testing for gene expression differences across cell types, and I would recommend a Z-test, which is directly computable from the C-SIDE output. The Z-statistic is computed is `Z = (m1 - m2)/sqrt(s1^2+s2^2)`. Where `m1,m2` are the estimated expression of each cell type, whereas `s1,s2` are the standard errors. This can then be converted to a p-value using the normal distribution CDF.
2. Could you elaborate on how procedure 2 works: "Then, Subgroup of epithelial cells were used to map 10x visium spot. then the weights of subgroup of epithelial cells should multiply total weights of the epithelial cell type ?" Do you mean that you are fitting RCTD using only the epithelial subtypes without including the endothelium subtype?
3. You could choose doublet mode as well, but as a practical consideration, it can often work better to have full mode for subtypes. This is for two reasons: first, subtypes are very similar, making it hard for doublet mode to distinguish. Second, subtypes of a cell type might not be discrete clusters, but could exist as a spectrum in between the subtype definitions.

Best,
Dylan

**Comment by khl0798** [comment]
Dear Dylan:
Thank you very much for you prompt reply.

1. For the second point, firstly, we mapped spot with the categories of cell types, and found that the epithelium and endothelium accounted for the main proportion, and the epithelium accounted for the highest proportion, for example, the epithelium accounted for about 50%. Then, after subdividing the epithelium, we mapped with the results of the subtypes of the epithelium（not include endothelium ）, and found that the proportion of the epithelium subtype ​1 and 2 was the highest, about 40%, 20%. Is it understood that the final ratio of epithelial subtype1 is 50%*40%=20%? and final ratio of epithelial subtype2 is 50%*20%=10% ?

 2. Another question  is, if only several subtypes of epithelial (excluding endothelium, etc.) are used for mapping, how can we understand the proportion of epithelial subtype 1 obtained ? 
 
3. for doublet mode, What is the difference between results$weights and results$weights_doublet.
 When I looked at the code, I found that for doublet mode, results@weights was calculated first, and then results@weights_doublet was recalculated for the first two major cell types selected.
What do first_class and second_class stand for ? 

![image](https://user-images.githubusercontent.com/7838505/180902418-de7fe06f-c882-42ee-9503-c41a34026197.png)

**Comment by dmcable** [comment]
Dear Candy,

Thanks, that helps to clarify things.

1. So I wouldn't recommend fitting the model with only epithelium subtypes since this would be unaware of the influence of the endothelium cell type. For example, an undesirable outcome would be using epithelium subtypes to compensate for endothelium marker genes. Instead, I would recommend including endothelium along with the epithelium subtypes (easiest to do in full mode). We will soon be releasing an update to handle subtype assignment automatically.
2. You can look at the weights assigned to each cell type, looking in either `results$weights` and `results$weights_doublet` for full and doublet mode, respectively.
3. You are correct for your description of `results@weights_doublet`. See also the point above. The `first_class` and `second_class` variables indicate whether a class level assignment has been made, which does not apply by default. In order to use class level assignments, which is another potential solution to your subtype problem, you can pass the `class_df` variable into the `create.RCTD` function. An example of the `class_df` variable is the `get_class_df` function in https://raw.githack.com/dmcable/spacexr/master/AnalysisPaper/MainFigures/figure2.html. For this variable, you should set the class of each epithelium subtype to be "epithelium". 

Best,
Dylan

**Comment by khl0798** [comment]
Dear Dylan,
Thank you very much for you prompt reply.
1. I tested the **class_df** you mentioned, as set in the following figure, the result is that first_class and second_class have some spot points with TRUE values, but the corresponding first_type and second_type do not have the information according to class_df?
 
![image](https://user-images.githubusercontent.com/7838505/181182838-ddca70e5-4a89-4333-9c16-c32c37f221da.png)

when first_class and second_class is TRUE, first_type and second_type It's still subtype information(for example ,first type Ductal 2? second type Fibroblasts 1?)


![image](https://user-images.githubusercontent.com/7838505/181182775-63ada163-1784-40c3-8387-5074a51c66eb.png)

by the way, May I ask that how  can i get the test data from https://raw.githack.com/dmcable/spacexr/master/AnalysisPaper/MainFigures/figure2.html ?

![image](https://user-images.githubusercontent.com/7838505/181183748-c2a163f0-b91b-4e46-a428-2bceebc600c6.png)

2. I will be looking forword to “subtype assignment automatically”. 


Many thanks.
Best,
Candy

**Comment by dmcable** [comment]
Hi Candy,

1. You are correct in your observations. When `first_class=TRUE`, the pixel can only be assigned confidently at the class level, but the top-performing subtype is still provided in `first_type` in case you wish to use that information. You can map back to cell class using the `class_df` mapping. For example, for the first pixel in your dataset, Ductal class is confidently assigned, and Ductal 2 is the most likely subtype, but cannot be determined with certainty.
2. The files you requested are located here: 
https://www.dropbox.com/s/3igvi3j85hbqz6z/Figure3.zip?dl=0 (Simulation test data)
https://www.dropbox.com/s/9e792keb3gz9sjo/Figure2.zip?dl=0 (Other files for figure 2)

Best,
Dylan

**Comment by khl0798** [comment]
Hi Dylan,
Thank you very much for you prompt reply.

when I test **run.CSIDE.single** according to 

https://github.com/dmcable/spacexr/blob/master/vignettes/CSIDE_celltocell_interactions.html, I got the error:

![image](https://user-images.githubusercontent.com/7838505/181289883-fde3fff3-f444-44c7-8283-90aee37dae2a.png)

Could you please help me find out the reason for this mistake? here is my code:
`
barcodes <- colnames(myRCTD@spatialRNA@counts)

cell_type <- 'Ductal 2'

explanatory.variable <- exvar.celltocell.interactions(myRCTD, barcodes, cell_type, radius = 50)

png('cell2cell_inter.png')

hist(explanatory.variable)

dev.off()

myRCTD <- run.CSIDE.single(myRCTD, explanatory.variable, gene_threshold = .01, 
                           cell_type_threshold = 10, fdr = 0.25)
`

![image](https://user-images.githubusercontent.com/7838505/181290223-f2a20705-dfdf-4100-9db4-1987b7a823f9.png)
![image](https://user-images.githubusercontent.com/7838505/181290243-1ff2c4e8-4464-475c-9843-e406919c4867.png)

the results of  head(explanatory.variable):

AAACCGGGTAGGTACC-1 AAACCGTTCGTCCAGG-1 AAACCTCATGAAGTTG-1 AAACGAAGAACATACC-1 
         0.3025316          0.3421117          0.2429988          0.5486319 
AAACGAGACGGTTGAT-1 AAACGGTTGCGAACTG-1 
         0.4863477          0.3997892

I'm sorry for asking so many questions, Your reply has also deepened my understanding of the use of this software

Many thanks

Best,
Candy

**Comment by dmcable** [comment]
Hi Candy,

The first thing that jumps out is that you are not running on many genes due to high `gene_threshold` value. I would recommend lowering to the default value of `gene_threshold = 5e-5`. Second, it is important to raise the value of `cell_type_threshold` to the default value of 125. This will ensure that there are enough pixels of each cell type to converge. I believe you used the parameters from the Vignette, but those are meant to be test parameters and for real data you want to use the default parameters (including `fdr`, which is .01 by default) as described above.

Best,
Dylan

**Comment by khl0798** [comment]
Hi Dylan，

thank you very much for your prompt reply.

 But infact , I can not understand the meaning " When first_class=TRUE, the pixel can only be assigned confidently at the class level, but the top-performing subtype is still provided in first_type in case you wish to use that information." ? 

In my understanding, wheather first_class=TRUE or first_class=FALSE or not,  the top-performing subtype is still provided in first_type when spot_class!='reject''?

**Comment by dmcable** [comment]
Hi Candy,

Yes, that is correct. The value of `first_type` will always contain the subtype, not the cell class. In order to get the cell class, you can use the `class_df` mapping. The value of `first_class` tells you whether you can trust the subtype assignment or only the cell class level.

Best,
Dylan

**Comment by khl0798** [comment]
Hi Dylan，

Thank you very much for providing us with the software **Spacexr**，and instruct me in detail, and I will try my best to learn the usage of this software.

Thanks again~

Best，
Candy
