### ISSUE TITLE
About spatial-transcriptomics tutorial

### ISSUE THREAD

**Issue by SuqinYang** [dmcable/spacexr#88]
Hi,sorry to trouble you.I am trying to use RCTD and I see the tutorial in “https://raw.githack.com/dmcable/spacexr/master/vignettes/spatial-transcriptomics.html”. But I don't know what the "coords" means in "Spatial Transcriptomics data" and how I get the coords from outs files of 10x spaceranger count.
Best wishes!

**Comment by khl0798** [comment]
Please allow me to answer this question as an observer, and forgive me if I make any mistakes. We'll wait for the author to help us out
10x spaceranger output：
 spatial https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/output/spatial
from this you can get tissue_positions.csv
![image](https://user-images.githubusercontent.com/7838505/179880399-38a7b593-7f0e-4092-b4a0-26bc34cf2b06.png)

**Comment by dmcable** [comment]
For 10x spaceranger, I recommend specifically using the function `read.VisiumSpatialRNA`. The way that `coords` are generated for Visium data is as follows:
`coords <- readr::read_csv(file = paste(datadir, "spatial/tissue_positions.csv",
                                         sep = "/"), col_names = TRUE)`
`colnames(coords) <- c("barcodes", "in_tissue", "x", "y", "pxl_col_in_fullres", "pxl_row_in_fullres")`
`coords <- tibble::column_to_rownames(coords, var = "barcodes")`
`coords <- coords[,c('x','y')]`
