### ISSUE TITLE
RCTD fails with error `the condition has length > 1`

### ISSUE THREAD

**Issue by scottgigante-immunai** [dmcable/spacexr#90]
RCTD is failing in [openproblems](https://github.com/giovp/SingleCellOpenProblems/runs/7408091744?check_suite_focus=true#step:18:1565) due to the below error. It appears the class test should be `!("dgCMatrix" %in% class(counts))` instead of `class(counts) != "dgCMatrix"`.

```
if (class(counts) != "dgCMatrix") { : 
    the condition has length > 1
  <error/rlang_error>
  Error:
  ! the condition has length > 1
  ---
  Backtrace:
      ▆
   1. └─`<fn>`(`<SnglCllE[,193]>`, `<SnglCllE[,100]>`)
   2.   └─spacexr::Reference(sc_counts, sc_cell_types)
   3.     └─spacexr:::check_counts(counts, "Reference", require_2d = T, require_int = require_int)
```

**Comment by tyleryasaka** [comment]
I just had this issue! What fixed it for me was making the counts table a data frame instead of a matrix. (The documentation says a matrix will work so that was a bit confusing.)

**Comment by dmcable** [comment]
thanks, looks good now
