### ISSUE TITLE
The explanatory variable/covariates preparation for "run.CSIDE.replicates"

### ISSUE THREAD

**Issue by glzhang90095** [dmcable/spacexr#95]
Hi!
This tool is so helpful to me. I have an issue when applying it to my data.
My design is to compare the cell-type specific DEGs between control vs disease using 10x VISIUM, 2 replicates for each group. 
I assume the "run.CSIDE.replicates" can compute the DEGs across conditions, not only within the section shown in the tutorial. When trying"run.CSIDE.replicates", I had difficulties in the prep of the explanatory variable/covariates. As suggested in the tutorial, the covariate needs to be biologically relevant to the gene changes and is very critical in the CSIDE running. The barcode ids in each section are the same. In this case, I think the spatial barcode is not available for covariates. 
Any suggestions on the covariates setup? 
If the "run.CSIDE.replicates" was not designed to do this job, is there any alternative way?

Thanks!
Guanglin

**Comment by dmcable** [comment]
The function `run.CSIDE.replicates` looks for differential expression within each section, for genes that replicate across multiple replicates. For the task you are describing of finding DE genes across replicates, the best way would be to merge all of your samples into on `SpatialRNA` object. Then, the explanatory variable, for each pixel, would denote the condition of each sample. If you run into naming conflicts for the barcodes, I recommend adding a sample ID prefix to each barcode. You could also e.g. use `run.CSIDE.replicates` with multiple replicates each paired together, though this requires at least 3 replicates per condition.

Dylan

**Comment by glzhang90095** [comment]
Hi Dylan @Dylan,
Forgive me for bringing this up again.
I followed your suggestions: merge the sections with each barcode prefixed with the condition, and **run.CSIDE.single** to get the differentially expressed genes among Control vs Disease at the cell type level. Correct if this is wrong. 

However, the number of DEGs is very few or zero for most cell types. So I was considering using the **run.CSIDE.replicates** to compare 4controls and 4 diseases. In the tutorial, you mentioned that "**we have the option to assign different replicates to** [different groups](https://raw.githack.com/dmcable/spacexr/master/vignettes/replicates.html) ". But in another [post](https://github.com/dmcable/spacexr/issues/100#issuecomment-1255768048), you said the use of group_ids for different groups is not available. 
I wondered if you could clarify which scenarios we can include different groups in **run.CSIDE.replicates**? Is **run.CSIDE.replicates** able to find DEGs across conditions in addition to the Z-test you mentioned in other [posts](https://github.com/dmcable/spacexr/issues/100#issuecomment-1255768048)?

Thanks a lot,
Guanglin

**Comment by dmcable** [comment]
The use of `group_ids` is intended for a different problem: estimating population DE (_within_ samples) when there are multiple samples and multiple replicates within each sample. It does not apply to this problem of DE _across_ conditions.

Yes, please refer to the Z-test method in other posts, as you identified, for an alternative way of accomplishing this task.
