### ISSUE TITLE
Error in solveIRWLS.weights

### ISSUE THREAD

**Issue by ZeroLi-Bio** [dmcable/spacexr#96]
Hi,

I was running RCTD on multimode and max_cores was set to 1 in order to prevent parallel error. I have 4  ST datasets and in same format, 3 was succesful while one encountered with this error: 

`Error in S[, i] : subscript out of bounds`
`Calls: run.RCTD ... process_bead_multi -> decompose_sparse -> solveIRWLS.weights`
`Execution halted`

Could you give me a hint on how to solve this?
Thanks a lot

**Comment by dmcable** [comment]
I'm not sure but if you send me the object and script, then I can try reproducing the error.

Dylan

**Comment by ZeroLi-Bio** [comment]
@dmcable 
Hi Dylan,

The object was uploaded to GoogleDrive here:
https://drive.google.com/file/d/16SYzJbtYkWm7CVeZLUe8xNQUg9jcIIyq/view?usp=sharing

and the codes are 
`library(spacexr)`
`load('myRCTD.Rdata')`
`myRCTD <- run.RCTD(myRCTD, doublet_mode = 'multi')`

Thanks for your help! 
Zeyu

**Comment by dmcable** [comment]
Hi, I have tracked the issue down to a problem with small numbers of total counts on these pixels (see attached image below). I have updated the code to throw an error in such a scenario, and to filter out such pixels in the creation of the object. It is worth thinking in your case why these pixels appeared.

You can see that for pixel 414, the total counts is 2, despite the UMI being 199:
<img width="861" alt="Screen Shot 2022-08-19 at 4 27 29 PM" src="https://user-images.githubusercontent.com/40443769/185710939-e36a15ba-ad12-4b0e-a387-70d63990d38f.png">

I would recommend filtering out these pixels, which is now default behavior.

**Comment by ZeroLi-Bio** [comment]
Appreciate a lot! I will try again on latest version. 
But what does the "bead" mean here? Is that meaning the number of celltypes or what? Could you explain it for a bit?
Thanks again. @dmcable

**Comment by dmcable** [comment]
Yes, so now this error indicates that something is wrong. Bead is synonymous with pixel (or spot). The `initial_weight_thresh`, set to .01 by default, is the amount of weight a cell type must have in full mode in order to be considered for multi mode. In this case, the weight of all cell types did not pass threshold. You can proceed by removing the cell types with small total counts, which is done automatically by the updated `create.RCTD` function.
