### ISSUE TITLE
Error in run.CSIDE and run.CSIDE.regions:task 1 failed - "invaild character indexing"

### ISSUE THREAD

**Issue by Lianqw** [dmcable/spacexr#97]
Hi,

I think this tool is interesting. I have an issue when applying it to my data. Could you give me a hint on how to solve this?
![image](https://user-images.githubusercontent.com/72534628/185597680-bf650579-4b32-438b-b7e2-c981430b9bc2.png)

Thanks a lot!
Lian

**Comment by dmcable** [comment]
Thank you, please upload the objects used to run this function so I can debug.

Dylan

**Comment by lqwszbd** [comment]
[data.zip](https://github.com/dmcable/spacexr/files/9416766/data.zip)
This is my data used to run this function and the code below is what I have used

myRCTD=readRDS("./myRCTD_mob.rds")
region_list = readRDS("./region_list.rds")
myRCTD <- run.CSIDE.regions(myRCTD, region_list,cell_types = c('OEC','Astro','N'), gene_threshold = .01, cell_type_threshold = 10, fdr = 0.25, doublet_mode = F, weight_threshold = 0.1) 

Thank you for your help!
Lian

**Comment by dmcable** [comment]
Hi, we have found the error and updated the code to better handle the error. The program now outputs the following on your data, which should explain how to fix the error:

<img width="1111" alt="Screen Shot 2022-08-24 at 7 01 59 PM" src="https://user-images.githubusercontent.com/40443769/186544814-a14b5e69-36b4-4798-affe-be61d941dc7b.png">
