### ISSUE TITLE
Spacexr Input data

### ISSUE THREAD

**Issue by JihyunKiminGithub** [dmcable/spacexr#99]
Dear spacexr developers,

Hello, First of all, thank you for making this amazing tool.

I have multiple visium slide and I want to use spot deconvolution function of this spacexr.
In the downstream analysis, I would normalize each visium slide by sctransform, merge and also want to batch correct by harmony.
At this point, Do you recommend me to use counts dataset of each visium slide or use batch corrected normalized dataset as a spacexr input dataset? Also, Do I need to combine all the normalized dataset and run spacexr function at once?

Thank you,
Jihyun.

**Comment by dmcable** [comment]
Hi Jihyun,

The tools in the spacexr package work on raw, unnormalized datasets. There
are also functions within spacexr to handle multiple slides at once.

Best,
Dylan
